/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1SearchParams,
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpSearchResponse
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getV1SearchResponse200 = {
  data: InternalHandlerHttpSearchResponse
  status: 200
}

export type getV1SearchResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1SearchResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type getV1SearchResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1SearchResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1SearchResponseSuccess = (getV1SearchResponse200) & {
  headers: Headers;
};
export type getV1SearchResponseError = (getV1SearchResponse401 | getV1SearchResponse422 | getV1SearchResponse429 | getV1SearchResponse500) & {
  headers: Headers;
};

export type getV1SearchResponse = (getV1SearchResponseSuccess | getV1SearchResponseError)

export const getGetV1SearchUrl = (params: GetV1SearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/search?${stringifiedParams}` : `/v1/search`
}

/**
 * Searches across friends (username/display_name trigram), group conversations (name substring), and messages (body full-text). The optional `types` query param caps the search to a comma-joined subset (`users`, `conversations`, `messages`); empty = all. Each section is hard-capped at 10 results so the mobile global-search modal renders fast — drill-downs use the per-section endpoints. Min query length: 2.
 * @summary Unified search
 */
export const getV1Search = async (params: GetV1SearchParams, options?: RequestInit): Promise<getV1SearchResponse> => {

  return orvalMutator<getV1SearchResponse>(getGetV1SearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1SearchQueryKey = (params?: GetV1SearchParams,) => {
    return [
    `/v1/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1SearchQueryOptions = <TData = Awaited<ReturnType<typeof getV1Search>>, TError = InternalHandlerHttpErrorResponse>(params: GetV1SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Search>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1SearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Search>>> = ({ signal }) => getV1Search(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Search>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1SearchQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Search>>>
export type GetV1SearchQueryError = InternalHandlerHttpErrorResponse


export function useGetV1Search<TData = Awaited<ReturnType<typeof getV1Search>>, TError = InternalHandlerHttpErrorResponse>(
 params: GetV1SearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Search>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Search>>,
          TError,
          Awaited<ReturnType<typeof getV1Search>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Search<TData = Awaited<ReturnType<typeof getV1Search>>, TError = InternalHandlerHttpErrorResponse>(
 params: GetV1SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Search>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Search>>,
          TError,
          Awaited<ReturnType<typeof getV1Search>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Search<TData = Awaited<ReturnType<typeof getV1Search>>, TError = InternalHandlerHttpErrorResponse>(
 params: GetV1SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Search>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Unified search
 */

export function useGetV1Search<TData = Awaited<ReturnType<typeof getV1Search>>, TError = InternalHandlerHttpErrorResponse>(
 params: GetV1SearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Search>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1SearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






