/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpPresenceListResponse,
  InternalHandlerHttpSetPresenceStatusRequest,
  InternalHandlerHttpWidgetFriendsResponse
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getV1PresenceFriendsResponse200 = {
  data: InternalHandlerHttpPresenceListResponse
  status: 200
}

export type getV1PresenceFriendsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1PresenceFriendsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1PresenceFriendsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1PresenceFriendsResponseSuccess = (getV1PresenceFriendsResponse200) & {
  headers: Headers;
};
export type getV1PresenceFriendsResponseError = (getV1PresenceFriendsResponse401 | getV1PresenceFriendsResponse429 | getV1PresenceFriendsResponse500) & {
  headers: Headers;
};

export type getV1PresenceFriendsResponse = (getV1PresenceFriendsResponseSuccess | getV1PresenceFriendsResponseError)

export const getGetV1PresenceFriendsUrl = () => {




  return `/v1/presence/friends`
}

/**
 * Returns one row per accepted friend with their current presence status (`online` / `away` / `offline` / `sleeping`) and `last_active_at`. Friends with no row yet surface as `offline`. Used on app open to populate the friend list immediately; the realtime stream then updates incrementally via §7.2 `presence.update`.
 * @summary List friends' presence
 */
export const getV1PresenceFriends = async ( options?: RequestInit): Promise<getV1PresenceFriendsResponse> => {

  return orvalMutator<getV1PresenceFriendsResponse>(getGetV1PresenceFriendsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1PresenceFriendsQueryKey = () => {
    return [
    `/v1/presence/friends`
    ] as const;
    }


export const getGetV1PresenceFriendsQueryOptions = <TData = Awaited<ReturnType<typeof getV1PresenceFriends>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PresenceFriends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1PresenceFriendsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1PresenceFriends>>> = ({ signal }) => getV1PresenceFriends({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1PresenceFriends>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1PresenceFriendsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1PresenceFriends>>>
export type GetV1PresenceFriendsQueryError = InternalHandlerHttpErrorResponse


export function useGetV1PresenceFriends<TData = Awaited<ReturnType<typeof getV1PresenceFriends>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PresenceFriends>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1PresenceFriends>>,
          TError,
          Awaited<ReturnType<typeof getV1PresenceFriends>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1PresenceFriends<TData = Awaited<ReturnType<typeof getV1PresenceFriends>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PresenceFriends>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1PresenceFriends>>,
          TError,
          Awaited<ReturnType<typeof getV1PresenceFriends>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1PresenceFriends<TData = Awaited<ReturnType<typeof getV1PresenceFriends>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PresenceFriends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List friends' presence
 */

export function useGetV1PresenceFriends<TData = Awaited<ReturnType<typeof getV1PresenceFriends>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1PresenceFriends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1PresenceFriendsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1PresenceStatusResponse204 = {
  data: void
  status: 204
}

export type postV1PresenceStatusResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1PresenceStatusResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1PresenceStatusResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1PresenceStatusResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1PresenceStatusResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1PresenceStatusResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1PresenceStatusResponseSuccess = (postV1PresenceStatusResponse204) & {
  headers: Headers;
};
export type postV1PresenceStatusResponseError = (postV1PresenceStatusResponse400 | postV1PresenceStatusResponse401 | postV1PresenceStatusResponse413 | postV1PresenceStatusResponse422 | postV1PresenceStatusResponse429 | postV1PresenceStatusResponse500) & {
  headers: Headers;
};

export type postV1PresenceStatusResponse = (postV1PresenceStatusResponseSuccess | postV1PresenceStatusResponseError)

export const getPostV1PresenceStatusUrl = () => {




  return `/v1/presence/status`
}

/**
 * Manual sticky-intent override. Allowed values: `online`, `away`, `sleeping`, `dnd`, or `null` to clear. `offline` is reserved for logout. Sticky values survive WS disconnect / decay so DND doesn't reset on app background. On a real change, the server publishes `presence.update` to every accepted friend (§7.2).
 * @summary Set my presence status
 */
export const postV1PresenceStatus = async (internalHandlerHttpSetPresenceStatusRequest: InternalHandlerHttpSetPresenceStatusRequest, options?: RequestInit): Promise<postV1PresenceStatusResponse> => {

  return orvalMutator<postV1PresenceStatusResponse>(getPostV1PresenceStatusUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpSetPresenceStatusRequest,)
  }
);}




export const getPostV1PresenceStatusMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PresenceStatus>>, TError,{data: InternalHandlerHttpSetPresenceStatusRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1PresenceStatus>>, TError,{data: InternalHandlerHttpSetPresenceStatusRequest}, TContext> => {

const mutationKey = ['postV1PresenceStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1PresenceStatus>>, {data: InternalHandlerHttpSetPresenceStatusRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1PresenceStatus(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1PresenceStatusMutationResult = NonNullable<Awaited<ReturnType<typeof postV1PresenceStatus>>>
    export type PostV1PresenceStatusMutationBody = InternalHandlerHttpSetPresenceStatusRequest
    export type PostV1PresenceStatusMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Set my presence status
 */
export const usePostV1PresenceStatus = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1PresenceStatus>>, TError,{data: InternalHandlerHttpSetPresenceStatusRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1PresenceStatus>>,
        TError,
        {data: InternalHandlerHttpSetPresenceStatusRequest},
        TContext
      > => {
      return useMutation(getPostV1PresenceStatusMutationOptions(options), queryClient);
    }
    export type getV1WidgetFriendsResponse200 = {
  data: InternalHandlerHttpWidgetFriendsResponse
  status: 200
}

export type getV1WidgetFriendsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1WidgetFriendsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1WidgetFriendsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1WidgetFriendsResponseSuccess = (getV1WidgetFriendsResponse200) & {
  headers: Headers;
};
export type getV1WidgetFriendsResponseError = (getV1WidgetFriendsResponse401 | getV1WidgetFriendsResponse429 | getV1WidgetFriendsResponse500) & {
  headers: Headers;
};

export type getV1WidgetFriendsResponse = (getV1WidgetFriendsResponseSuccess | getV1WidgetFriendsResponseError)

export const getGetV1WidgetFriendsUrl = () => {




  return `/v1/widget/friends`
}

/**
 * Mobile widget endpoint per §6.1. Returns one row per accepted friend, embedding the public user profile alongside their presence state — designed for a low-frequency poll (~15min) that wants everything for the widget UI in one shape.
 * @summary Widget feed (friends + presence)
 */
export const getV1WidgetFriends = async ( options?: RequestInit): Promise<getV1WidgetFriendsResponse> => {

  return orvalMutator<getV1WidgetFriendsResponse>(getGetV1WidgetFriendsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1WidgetFriendsQueryKey = () => {
    return [
    `/v1/widget/friends`
    ] as const;
    }


export const getGetV1WidgetFriendsQueryOptions = <TData = Awaited<ReturnType<typeof getV1WidgetFriends>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1WidgetFriends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1WidgetFriendsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1WidgetFriends>>> = ({ signal }) => getV1WidgetFriends({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1WidgetFriends>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1WidgetFriendsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1WidgetFriends>>>
export type GetV1WidgetFriendsQueryError = InternalHandlerHttpErrorResponse


export function useGetV1WidgetFriends<TData = Awaited<ReturnType<typeof getV1WidgetFriends>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1WidgetFriends>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1WidgetFriends>>,
          TError,
          Awaited<ReturnType<typeof getV1WidgetFriends>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1WidgetFriends<TData = Awaited<ReturnType<typeof getV1WidgetFriends>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1WidgetFriends>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1WidgetFriends>>,
          TError,
          Awaited<ReturnType<typeof getV1WidgetFriends>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1WidgetFriends<TData = Awaited<ReturnType<typeof getV1WidgetFriends>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1WidgetFriends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Widget feed (friends + presence)
 */

export function useGetV1WidgetFriends<TData = Awaited<ReturnType<typeof getV1WidgetFriends>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1WidgetFriends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1WidgetFriendsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






