run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errorlint
    - gocritic
    - gofmt
    - goimports
    - misspell
    - revive
    - sqlclosecheck
    - rowserrcheck

linters-settings:
  errorlint:
    asserts: true
    comparison: true
