/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalHandlerHttpDeviceTokenListResponse,
  InternalHandlerHttpDeviceTokenResponse,
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpRegisterDeviceRequest,
  InternalHandlerHttpRegisterVoIPTokenRequest,
  InternalHandlerHttpVoIPTokenResponse
} from '../../model';

import { orvalMutator } from '../../orval-mutator';




export type getV1DevicesResponse200 = {
  data: InternalHandlerHttpDeviceTokenListResponse
  status: 200
}

export type getV1DevicesResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1DevicesResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1DevicesResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1DevicesResponseSuccess = (getV1DevicesResponse200) & {
  headers: Headers;
};
export type getV1DevicesResponseError = (getV1DevicesResponse401 | getV1DevicesResponse429 | getV1DevicesResponse500) & {
  headers: Headers;
};

export type getV1DevicesResponse = (getV1DevicesResponseSuccess | getV1DevicesResponseError)

export const getGetV1DevicesUrl = () => {




  return `/v1/devices`
}

/**
 * Returns every device token registered to the authenticated user, newest first. Pair with `DELETE /v1/devices/{id}` to revoke.
 * @summary List my device tokens
 */
export const getV1Devices = async ( options?: RequestInit): Promise<getV1DevicesResponse> => {

  return orvalMutator<getV1DevicesResponse>(getGetV1DevicesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1DevicesQueryKey = () => {
    return [
    `/v1/devices`
    ] as const;
    }


export const getGetV1DevicesQueryOptions = <TData = Awaited<ReturnType<typeof getV1Devices>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Devices>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1DevicesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Devices>>> = ({ signal }) => getV1Devices({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Devices>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1DevicesQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Devices>>>
export type GetV1DevicesQueryError = InternalHandlerHttpErrorResponse


export function useGetV1Devices<TData = Awaited<ReturnType<typeof getV1Devices>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Devices>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Devices>>,
          TError,
          Awaited<ReturnType<typeof getV1Devices>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Devices<TData = Awaited<ReturnType<typeof getV1Devices>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Devices>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Devices>>,
          TError,
          Awaited<ReturnType<typeof getV1Devices>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Devices<TData = Awaited<ReturnType<typeof getV1Devices>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Devices>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List my device tokens
 */

export function useGetV1Devices<TData = Awaited<ReturnType<typeof getV1Devices>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Devices>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1DevicesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1DevicesResponse201 = {
  data: InternalHandlerHttpDeviceTokenResponse
  status: 201
}

export type postV1DevicesResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1DevicesResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1DevicesResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1DevicesResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1DevicesResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1DevicesResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1DevicesResponseSuccess = (postV1DevicesResponse201) & {
  headers: Headers;
};
export type postV1DevicesResponseError = (postV1DevicesResponse400 | postV1DevicesResponse401 | postV1DevicesResponse413 | postV1DevicesResponse422 | postV1DevicesResponse429 | postV1DevicesResponse500) & {
  headers: Headers;
};

export type postV1DevicesResponse = (postV1DevicesResponseSuccess | postV1DevicesResponseError)

export const getPostV1DevicesUrl = () => {




  return `/v1/devices`
}

/**
 * Stores (or refreshes) the caller's Expo push token + platform per §6.1. Idempotent on the (user_id, expo_token) pair: re-registering the same token from the same user updates `last_seen_at` and refreshes the platform rather than creating a duplicate row, so mobile clients can call this on every cold start without bloating the table. Returns the persisted row including its server-issued `id`, which the client uses to call DELETE /v1/devices/{id} on logout.
 * @summary Register a device's Expo push token
 */
export const postV1Devices = async (internalHandlerHttpRegisterDeviceRequest: InternalHandlerHttpRegisterDeviceRequest, options?: RequestInit): Promise<postV1DevicesResponse> => {

  return orvalMutator<postV1DevicesResponse>(getPostV1DevicesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpRegisterDeviceRequest,)
  }
);}




export const getPostV1DevicesMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Devices>>, TError,{data: InternalHandlerHttpRegisterDeviceRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1Devices>>, TError,{data: InternalHandlerHttpRegisterDeviceRequest}, TContext> => {

const mutationKey = ['postV1Devices'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1Devices>>, {data: InternalHandlerHttpRegisterDeviceRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1Devices(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1DevicesMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Devices>>>
    export type PostV1DevicesMutationBody = InternalHandlerHttpRegisterDeviceRequest
    export type PostV1DevicesMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Register a device's Expo push token
 */
export const usePostV1Devices = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Devices>>, TError,{data: InternalHandlerHttpRegisterDeviceRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1Devices>>,
        TError,
        {data: InternalHandlerHttpRegisterDeviceRequest},
        TContext
      > => {
      return useMutation(getPostV1DevicesMutationOptions(options), queryClient);
    }
    export type postV1DevicesVoipResponse201 = {
  data: InternalHandlerHttpVoIPTokenResponse
  status: 201
}

export type postV1DevicesVoipResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1DevicesVoipResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1DevicesVoipResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1DevicesVoipResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1DevicesVoipResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1DevicesVoipResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1DevicesVoipResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1DevicesVoipResponseSuccess = (postV1DevicesVoipResponse201) & {
  headers: Headers;
};
export type postV1DevicesVoipResponseError = (postV1DevicesVoipResponse400 | postV1DevicesVoipResponse401 | postV1DevicesVoipResponse404 | postV1DevicesVoipResponse413 | postV1DevicesVoipResponse422 | postV1DevicesVoipResponse429 | postV1DevicesVoipResponse500) & {
  headers: Headers;
};

export type postV1DevicesVoipResponse = (postV1DevicesVoipResponseSuccess | postV1DevicesVoipResponseError)

export const getPostV1DevicesVoipUrl = () => {




  return `/v1/devices/voip`
}

/**
 * Stores (or refreshes) the caller's iOS PushKit token. Idempotent on (user_id, voip_token): re-registering the same token bumps `last_seen_at`. Required for the §8.6 CallKit incoming-call ring on iOS — Apple's PushKit transport wakes the app from a fully-killed state, which APNS / Expo push can't do.
 * @summary Register an iOS PushKit (VoIP) token
 */
export const postV1DevicesVoip = async (internalHandlerHttpRegisterVoIPTokenRequest: InternalHandlerHttpRegisterVoIPTokenRequest, options?: RequestInit): Promise<postV1DevicesVoipResponse> => {

  return orvalMutator<postV1DevicesVoipResponse>(getPostV1DevicesVoipUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpRegisterVoIPTokenRequest,)
  }
);}




export const getPostV1DevicesVoipMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1DevicesVoip>>, TError,{data: InternalHandlerHttpRegisterVoIPTokenRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1DevicesVoip>>, TError,{data: InternalHandlerHttpRegisterVoIPTokenRequest}, TContext> => {

const mutationKey = ['postV1DevicesVoip'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1DevicesVoip>>, {data: InternalHandlerHttpRegisterVoIPTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1DevicesVoip(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1DevicesVoipMutationResult = NonNullable<Awaited<ReturnType<typeof postV1DevicesVoip>>>
    export type PostV1DevicesVoipMutationBody = InternalHandlerHttpRegisterVoIPTokenRequest
    export type PostV1DevicesVoipMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Register an iOS PushKit (VoIP) token
 */
export const usePostV1DevicesVoip = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1DevicesVoip>>, TError,{data: InternalHandlerHttpRegisterVoIPTokenRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1DevicesVoip>>,
        TError,
        {data: InternalHandlerHttpRegisterVoIPTokenRequest},
        TContext
      > => {
      return useMutation(getPostV1DevicesVoipMutationOptions(options), queryClient);
    }
    export type deleteV1DevicesIdResponse204 = {
  data: void
  status: 204
}

export type deleteV1DevicesIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type deleteV1DevicesIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1DevicesIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type deleteV1DevicesIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1DevicesIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1DevicesIdResponseSuccess = (deleteV1DevicesIdResponse204) & {
  headers: Headers;
};
export type deleteV1DevicesIdResponseError = (deleteV1DevicesIdResponse400 | deleteV1DevicesIdResponse401 | deleteV1DevicesIdResponse404 | deleteV1DevicesIdResponse429 | deleteV1DevicesIdResponse500) & {
  headers: Headers;
};

export type deleteV1DevicesIdResponse = (deleteV1DevicesIdResponseSuccess | deleteV1DevicesIdResponseError)

export const getDeleteV1DevicesIdUrl = (id: string,) => {




  return `/v1/devices/${id}`
}

/**
 * Removes the caller's device token by `id` (returned from POST /v1/devices). Scoped to the authenticated user — passing another user's id surfaces as 404 to avoid enumeration. The mobile client calls this on logout so we stop pushing to a device the user signed out of.
 * @summary Delete a device token
 */
export const deleteV1DevicesId = async (id: string, options?: RequestInit): Promise<deleteV1DevicesIdResponse> => {

  return orvalMutator<deleteV1DevicesIdResponse>(getDeleteV1DevicesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1DevicesIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1DevicesId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1DevicesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteV1DevicesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1DevicesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteV1DevicesId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1DevicesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1DevicesId>>>

    export type DeleteV1DevicesIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Delete a device token
 */
export const useDeleteV1DevicesId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1DevicesId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1DevicesId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteV1DevicesIdMutationOptions(options), queryClient);
    }
