/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpJoinRoomRequest,
  InternalHandlerHttpJoinRoomResponse,
  InternalHandlerHttpRoomStateResponse
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getV1ConversationsIdRoomResponse200 = {
  data: InternalHandlerHttpRoomStateResponse
  status: 200
}

export type getV1ConversationsIdRoomResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1ConversationsIdRoomResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1ConversationsIdRoomResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getV1ConversationsIdRoomResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1ConversationsIdRoomResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1ConversationsIdRoomResponseSuccess = (getV1ConversationsIdRoomResponse200) & {
  headers: Headers;
};
export type getV1ConversationsIdRoomResponseError = (getV1ConversationsIdRoomResponse400 | getV1ConversationsIdRoomResponse401 | getV1ConversationsIdRoomResponse404 | getV1ConversationsIdRoomResponse429 | getV1ConversationsIdRoomResponse500) & {
  headers: Headers;
};

export type getV1ConversationsIdRoomResponse = (getV1ConversationsIdRoomResponseSuccess | getV1ConversationsIdRoomResponseError)

export const getGetV1ConversationsIdRoomUrl = (id: string,) => {




  return `/v1/conversations/${id}/room`
}

/**
 * Returns the current participant list (with `joined_at` and `video` flags) plus `started_at` for the conversation's persistent room (§10.3). Membership-gated; non-members get 404.
 * @summary Get a conversation's room state
 */
export const getV1ConversationsIdRoom = async (id: string, options?: RequestInit): Promise<getV1ConversationsIdRoomResponse> => {

  return orvalMutator<getV1ConversationsIdRoomResponse>(getGetV1ConversationsIdRoomUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1ConversationsIdRoomQueryKey = (id: string,) => {
    return [
    `/v1/conversations/${id}/room`
    ] as const;
    }


export const getGetV1ConversationsIdRoomQueryOptions = <TData = Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError = InternalHandlerHttpErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1ConversationsIdRoomQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1ConversationsIdRoom>>> = ({ signal }) => getV1ConversationsIdRoom(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1ConversationsIdRoomQueryResult = NonNullable<Awaited<ReturnType<typeof getV1ConversationsIdRoom>>>
export type GetV1ConversationsIdRoomQueryError = InternalHandlerHttpErrorResponse


export function useGetV1ConversationsIdRoom<TData = Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1ConversationsIdRoom>>,
          TError,
          Awaited<ReturnType<typeof getV1ConversationsIdRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1ConversationsIdRoom<TData = Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1ConversationsIdRoom>>,
          TError,
          Awaited<ReturnType<typeof getV1ConversationsIdRoom>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1ConversationsIdRoom<TData = Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a conversation's room state
 */

export function useGetV1ConversationsIdRoom<TData = Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdRoom>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1ConversationsIdRoomQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1ConversationsIdRoomJoinResponse200 = {
  data: InternalHandlerHttpJoinRoomResponse
  status: 200
}

export type postV1ConversationsIdRoomJoinResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1ConversationsIdRoomJoinResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1ConversationsIdRoomJoinResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1ConversationsIdRoomJoinResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1ConversationsIdRoomJoinResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1ConversationsIdRoomJoinResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1ConversationsIdRoomJoinResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1ConversationsIdRoomJoinResponseSuccess = (postV1ConversationsIdRoomJoinResponse200) & {
  headers: Headers;
};
export type postV1ConversationsIdRoomJoinResponseError = (postV1ConversationsIdRoomJoinResponse400 | postV1ConversationsIdRoomJoinResponse401 | postV1ConversationsIdRoomJoinResponse404 | postV1ConversationsIdRoomJoinResponse413 | postV1ConversationsIdRoomJoinResponse422 | postV1ConversationsIdRoomJoinResponse429 | postV1ConversationsIdRoomJoinResponse500) & {
  headers: Headers;
};

export type postV1ConversationsIdRoomJoinResponse = (postV1ConversationsIdRoomJoinResponseSuccess | postV1ConversationsIdRoomJoinResponseError)

export const getPostV1ConversationsIdRoomJoinUrl = (id: string,) => {




  return `/v1/conversations/${id}/room/join`
}

/**
 * Issues a LiveKit JWT scoped to this conversation's persistent room (§10.3 — the room name is `conv:<conversation_id>`, returned verbatim in the response's `room_id` field; the prefix lets ops tell call rooms apart from any other LiveKit room name we may add later). The caller must be a member; non-members get 404 (no enumeration leak). Token TTL is 10 minutes; LiveKit auto-refreshes during the connection. The `video` flag is a UI hint baked into the JWT metadata so other participants can render the camera-on indicator — token publish permissions are identical regardless.
 * @summary Join a conversation's room
 */
export const postV1ConversationsIdRoomJoin = async (id: string,
    internalHandlerHttpJoinRoomRequest?: InternalHandlerHttpJoinRoomRequest, options?: RequestInit): Promise<postV1ConversationsIdRoomJoinResponse> => {

  return orvalMutator<postV1ConversationsIdRoomJoinResponse>(getPostV1ConversationsIdRoomJoinUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpJoinRoomRequest,)
  }
);}




export const getPostV1ConversationsIdRoomJoinMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRoomJoin>>, TError,{id: string;data?: InternalHandlerHttpJoinRoomRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRoomJoin>>, TError,{id: string;data?: InternalHandlerHttpJoinRoomRequest}, TContext> => {

const mutationKey = ['postV1ConversationsIdRoomJoin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1ConversationsIdRoomJoin>>, {id: string;data?: InternalHandlerHttpJoinRoomRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1ConversationsIdRoomJoin(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ConversationsIdRoomJoinMutationResult = NonNullable<Awaited<ReturnType<typeof postV1ConversationsIdRoomJoin>>>
    export type PostV1ConversationsIdRoomJoinMutationBody = InternalHandlerHttpJoinRoomRequest | undefined
    export type PostV1ConversationsIdRoomJoinMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Join a conversation's room
 */
export const usePostV1ConversationsIdRoomJoin = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRoomJoin>>, TError,{id: string;data?: InternalHandlerHttpJoinRoomRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1ConversationsIdRoomJoin>>,
        TError,
        {id: string;data?: InternalHandlerHttpJoinRoomRequest},
        TContext
      > => {
      return useMutation(getPostV1ConversationsIdRoomJoinMutationOptions(options), queryClient);
    }
    export type postV1ConversationsIdRoomLeaveResponse204 = {
  data: void
  status: 204
}

export type postV1ConversationsIdRoomLeaveResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1ConversationsIdRoomLeaveResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1ConversationsIdRoomLeaveResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1ConversationsIdRoomLeaveResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1ConversationsIdRoomLeaveResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1ConversationsIdRoomLeaveResponseSuccess = (postV1ConversationsIdRoomLeaveResponse204) & {
  headers: Headers;
};
export type postV1ConversationsIdRoomLeaveResponseError = (postV1ConversationsIdRoomLeaveResponse400 | postV1ConversationsIdRoomLeaveResponse401 | postV1ConversationsIdRoomLeaveResponse404 | postV1ConversationsIdRoomLeaveResponse429 | postV1ConversationsIdRoomLeaveResponse500) & {
  headers: Headers;
};

export type postV1ConversationsIdRoomLeaveResponse = (postV1ConversationsIdRoomLeaveResponseSuccess | postV1ConversationsIdRoomLeaveResponseError)

export const getPostV1ConversationsIdRoomLeaveUrl = (id: string,) => {




  return `/v1/conversations/${id}/room/leave`
}

/**
 * Best-effort cleanup — the LiveKit `participant_left` webhook is the source of truth for the participant set, so this endpoint exists primarily to give the client a stable place to record an explicit leave intent. Membership is still checked so non-members can't poke at room state.
 * @summary Leave a conversation's room
 */
export const postV1ConversationsIdRoomLeave = async (id: string, options?: RequestInit): Promise<postV1ConversationsIdRoomLeaveResponse> => {

  return orvalMutator<postV1ConversationsIdRoomLeaveResponse>(getPostV1ConversationsIdRoomLeaveUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1ConversationsIdRoomLeaveMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRoomLeave>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRoomLeave>>, TError,{id: string}, TContext> => {

const mutationKey = ['postV1ConversationsIdRoomLeave'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1ConversationsIdRoomLeave>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postV1ConversationsIdRoomLeave(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ConversationsIdRoomLeaveMutationResult = NonNullable<Awaited<ReturnType<typeof postV1ConversationsIdRoomLeave>>>

    export type PostV1ConversationsIdRoomLeaveMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Leave a conversation's room
 */
export const usePostV1ConversationsIdRoomLeave = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRoomLeave>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1ConversationsIdRoomLeave>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostV1ConversationsIdRoomLeaveMutationOptions(options), queryClient);
    }
