// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/login": {
            "post": {
                "description": "Verifies credentials and binds a session cookie. Same generic 401 for any failure path (no enumeration).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.LoginResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed JSON / empty body",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request body too large",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Destroys the current session cookie. Idempotent — missing session returns 204.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out current session",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Destroys every active session for the authenticated user. Used for \"sign out everywhere\" or post-password-reset cleanup.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out every active session for this user",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the user backing the active session. Use this on app launch to populate the local user store.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get authenticated user",
                "responses": {
                    "200": {
                        "description": "Authenticated user",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.MeResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/password-reset/confirm": {
            "post": {
                "description": "Sets the user's new password if the token is valid + unused. Returns generic 401 on any failure (no oracle).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm a password reset",
                "parameters": [
                    {
                        "description": "Token + new password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.PasswordResetConfirmRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed JSON / empty body",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired reset token",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request body too large",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/password-reset/request": {
            "post": {
                "description": "Generates a reset token and emails it. Always returns 204 even when the email is unknown — defeats account enumeration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Request a password reset",
                "parameters": [
                    {
                        "description": "Email to send the reset link to",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.PasswordResetRequestRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed JSON / empty body",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request body too large",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/auth/register": {
            "post": {
                "description": "Creates a new user account, hashes the password with argon2id, and binds the new session cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c\"",
                        "description": "Idempotency key (UUID v7); enables safe retries",
                        "name": "Idempotency-Key",
                        "in": "header"
                    },
                    {
                        "description": "Registration payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.RegisterResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed JSON / empty body",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Username or email already taken",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request body too large",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/friends": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the caller's accepted friendships keyset-paginated by ` + "`" + `accepted_at DESC, id DESC` + "`" + ` per §6.4. Each row embeds the counterparty's public profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "List accepted friends",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 20,
                        "description": "Page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"eyJpZCI6IjAxOTJmNWEzLTdjMWItN2EzZi05YjFjLTJkM2U0ZjVhNmI3YyIsInRzIjoiMjAyNi0wNS0wMlQwOTozMToyMS44MTBaIn0=\"",
                        "description": "Opaque pagination cursor from a previous response",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of friendships",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.FriendListResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid limit or cursor",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/friends/requests": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the caller's pending friend requests partitioned into ` + "`" + `incoming` + "`" + ` (where the caller is the addressee) and ` + "`" + `outgoing` + "`" + ` (where the caller is the requester).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "List pending friend requests",
                "responses": {
                    "200": {
                        "description": "Pending requests",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.FriendRequestsResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Creates a ` + "`" + `pending` + "`" + ` friendship from the caller to the user with ` + "`" + `username` + "`" + `. Returns 409 if a friendship already exists in either direction (including blocks — the response is generic so block existence isn't leaked).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Send a friend request",
                "parameters": [
                    {
                        "description": "Target username",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.SendFriendRequestRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Pending friendship",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.FriendshipResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed JSON / empty body",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Target user not found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Friendship already exists or blocked",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request body too large",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/friends/requests/{id}/accept": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Accept a friend request",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c\"",
                        "description": "Friendship id (UUID v7)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Accepted friendship",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.FriendshipResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed friendship id",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Caller is not the addressee",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Friend request not found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Friend request is not pending",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/friends/requests/{id}/decline": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Decline a friend request",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c\"",
                        "description": "Friendship id (UUID v7)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed friendship id",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Caller is not the addressee",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Friend request not found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Friend request is not pending",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/friends/{user_id}": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Unfriend a user",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c\"",
                        "description": "Counterparty user id (UUID v7)",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed user id",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No friendship between these users",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Friendship is pending or blocked, not accepted",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Cannot unfriend yourself",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/friends/{user_id}/block": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Records the caller as having blocked the target. Replaces any pending/accepted friendship between the two. Refuses (403) if the target has already blocked the caller — the existing block stays in place and the response is intentionally generic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Block a user",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c\"",
                        "description": "User id to block (UUID v7)",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Block row",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.FriendshipResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed user id",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Target has already blocked the caller",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Target user not found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Concurrent write conflict; retry",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Cannot block yourself",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Removes the caller's block on the target user. The target party can't call this — only the original blocker can.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "friends"
                ],
                "summary": "Unblock a user",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c\"",
                        "description": "User id to unblock (UUID v7)",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed user id",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No block by the caller exists for this user",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Cannot unblock yourself",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/healthz": {
            "get": {
                "description": "Returns 200 unconditionally. The load balancer uses this to confirm the process is running; it does not check downstream dependencies (use readyz for that).",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/openapi.json": {
            "get": {
                "description": "Serves the generated OpenAPI 2.0 spec for this API. /v1/docs (Swagger UI) loads it from this endpoint.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "OpenAPI spec",
                "responses": {
                    "200": {
                        "description": "OpenAPI document",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/readyz": {
            "get": {
                "description": "Pings Postgres and Redis with independent 1.5s timeouts. Returns 200 only when both respond; otherwise 500 with a §4.4 envelope listing failed dependencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Dependency failure",
                        "schema": {
                            "$ref": "#/definitions/github_com_cadenlund_wakeup_apps_backend_internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns up to ` + "`" + `limit` + "`" + ` users whose username or display_name matches ` + "`" + `q` + "`" + ` (case-insensitive trigram). Empty ` + "`" + `q` + "`" + ` returns the catalog ordered by ` + "`" + `created_at DESC, id DESC` + "`" + `. Pagination is keyset (§6.4) — never offset.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Search users",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"caden\"",
                        "description": "Search prefix",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 20,
                        "description": "Page size (default 20, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "\"eyJpZCI6IjAxOTJmNWEzLTdjMWItN2EzZi05YjFjLTJkM2U0ZjVhNmI3YyIsInRzIjoiMjAyNi0wNS0wMlQwOTozMToyMS44MTBaIn0=\"",
                        "description": "Opaque pagination cursor from a previous response",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Page of users",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.UserListResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid limit or cursor",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/me": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Soft-deletes the authenticated user. Their content (messages, etc.) is preserved per §4.6 but they become invisible to lists/search and cannot log in.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Soft-delete current user",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Blocked during admin impersonation",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Patches ` + "`" + `display_name` + "`" + `, ` + "`" + `avatar_url` + "`" + `, or ` + "`" + `color_scheme` + "`" + `. Each field is optional; nil values are left unchanged.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update current user's profile",
                "parameters": [
                    {
                        "description": "Profile patch",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.UpdateMeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated profile",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.MeResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed JSON / empty body",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request body too large",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/me/avatar": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Accepts a multipart form with a single ` + "`" + `file` + "`" + ` field. Max 5 MiB; server-side MIME detection (§9.2) accepts image/png, image/jpeg, image/gif, image/webp.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Upload current user's avatar",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Avatar file (max 5 MiB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User with new avatar_url",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.AvatarUploadResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or empty ` + "`" + `file` + "`" + ` field",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Avatar exceeds 5 MiB cap",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Disallowed content-type",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/me/notifications": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the per-category push-notification toggles. The row is auto-created with defaults (all true) on first read.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get current user's notification preferences",
                "responses": {
                    "200": {
                        "description": "Notification toggles",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.NotificationPreferencesResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Patches any subset of ` + "`" + `direct_messages` + "`" + `, ` + "`" + `group_messages` + "`" + `, ` + "`" + `friend_requests` + "`" + `, ` + "`" + `calls` + "`" + `. Omitted fields are unchanged.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update current user's notification preferences",
                "parameters": [
                    {
                        "description": "Toggles patch",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.UpdateNotificationPreferencesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated toggles",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.NotificationPreferencesResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed JSON / empty body",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Request body too large",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the public profile (username, display_name, avatar). Soft-deleted users collapse to the placeholder shape (§4.6).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by id",
                "parameters": [
                    {
                        "type": "string",
                        "example": "\"0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c\"",
                        "description": "User id (UUID v7)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Public profile",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.UserResponse"
                        },
                        "headers": {
                            "X-Request-ID": {
                                "type": "string",
                                "description": "Echoed request id"
                            }
                        }
                    },
                    "400": {
                        "description": "Malformed id",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Rate limited",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_cadenlund_wakeup_apps_backend_internal_handler_http.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "RESOURCE_NOT_FOUND"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cadenlund_wakeup_apps_backend_internal_handler_http.ErrorField"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "user not found"
                },
                "retry_after_seconds": {
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "github_com_cadenlund_wakeup_apps_backend_internal_handler_http.ErrorField": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_FORMAT"
                },
                "field": {
                    "type": "string",
                    "example": "email"
                },
                "message": {
                    "type": "string",
                    "example": "must be a valid email"
                }
            }
        },
        "github_com_cadenlund_wakeup_apps_backend_internal_handler_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_cadenlund_wakeup_apps_backend_internal_handler_http.ErrorBody"
                }
            }
        },
        "internal_handler_http.AvatarUploadResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/internal_handler_http.MeResponse"
                }
            }
        },
        "internal_handler_http.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "RESOURCE_NOT_FOUND"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler_http.ErrorField"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "user not found"
                },
                "retry_after_seconds": {
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "internal_handler_http.ErrorField": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_FORMAT"
                },
                "field": {
                    "type": "string",
                    "example": "email"
                },
                "message": {
                    "type": "string",
                    "example": "must be a valid email"
                }
            }
        },
        "internal_handler_http.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_handler_http.ErrorBody"
                }
            }
        },
        "internal_handler_http.FriendListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler_http.FriendshipResponse"
                    }
                },
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "next_cursor": {
                    "type": "string",
                    "example": "eyJpZCI6IjAxOTJmNWEzLTdjMWItN2EzZi05YjFjLTJkM2U0ZjVhNmI3YyIsInRzIjoiMjAyNi0wNS0wMlQwOTozMToyMS44MTBaIn0="
                }
            }
        },
        "internal_handler_http.FriendRequestsResponse": {
            "type": "object",
            "properties": {
                "incoming": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler_http.FriendshipResponse"
                    }
                },
                "outgoing": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler_http.FriendshipResponse"
                    }
                }
            }
        },
        "internal_handler_http.FriendshipResponse": {
            "type": "object",
            "properties": {
                "accepted_at": {
                    "type": "string",
                    "example": "2026-05-02T09:35:11.221Z"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-02T09:31:21.810Z"
                },
                "id": {
                    "type": "string",
                    "example": "0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c"
                },
                "status": {
                    "type": "string",
                    "example": "accepted"
                },
                "user": {
                    "$ref": "#/definitions/internal_handler_http.UserResponse"
                }
            }
        },
        "internal_handler_http.ImpersonatorInfo": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string",
                    "example": "Baron Admin"
                },
                "id": {
                    "type": "string",
                    "example": "0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c"
                },
                "username": {
                    "type": "string",
                    "example": "baron"
                }
            }
        },
        "internal_handler_http.LoginRequest": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string",
                    "maxLength": 254,
                    "minLength": 3,
                    "example": "caden"
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 1,
                    "example": "correct-horse-battery-staple"
                }
            }
        },
        "internal_handler_http.LoginResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/internal_handler_http.MeResponse"
                }
            }
        },
        "internal_handler_http.MeResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://wakeup.app/avatars/caden.png"
                },
                "color_scheme": {
                    "type": "string",
                    "example": "system"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-02T09:31:21.810Z"
                },
                "display_name": {
                    "type": "string",
                    "example": "Caden Lund"
                },
                "email": {
                    "type": "string",
                    "example": "caden@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c"
                },
                "impersonated_by": {
                    "$ref": "#/definitions/internal_handler_http.ImpersonatorInfo"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "username": {
                    "type": "string",
                    "example": "caden"
                }
            }
        },
        "internal_handler_http.NotificationPreferencesResponse": {
            "type": "object",
            "properties": {
                "calls": {
                    "type": "boolean",
                    "example": true
                },
                "direct_messages": {
                    "type": "boolean",
                    "example": true
                },
                "friend_requests": {
                    "type": "boolean",
                    "example": true
                },
                "group_messages": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handler_http.PasswordResetConfirmRequest": {
            "type": "object",
            "required": [
                "new_password",
                "token"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8,
                    "example": "new-correct-horse-battery"
                },
                "token": {
                    "type": "string",
                    "maxLength": 512,
                    "minLength": 1,
                    "example": "3f8a1c2d9e6b4f2a8d1c7b3e9f5a2c4d3f8a1c2d9e6b4f2a8d1c7b3e9f5a2c4d"
                }
            }
        },
        "internal_handler_http.PasswordResetRequestRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "maxLength": 254,
                    "example": "caden@example.com"
                }
            }
        },
        "internal_handler_http.RegisterRequest": {
            "type": "object",
            "required": [
                "display_name",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "display_name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1,
                    "example": "Caden Lund"
                },
                "email": {
                    "type": "string",
                    "maxLength": 254,
                    "example": "caden@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 128,
                    "minLength": 8,
                    "example": "correct-horse-battery-staple"
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3,
                    "example": "caden"
                }
            }
        },
        "internal_handler_http.RegisterResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/internal_handler_http.MeResponse"
                }
            }
        },
        "internal_handler_http.SendFriendRequestRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3,
                    "example": "baron"
                }
            }
        },
        "internal_handler_http.UpdateMeRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "maxLength": 2048,
                    "example": "https://wakeup.app/avatars/caden.png"
                },
                "color_scheme": {
                    "type": "string",
                    "enum": [
                        "light",
                        "dark",
                        "system"
                    ],
                    "example": "dark"
                },
                "display_name": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1,
                    "example": "Caden Lund"
                }
            }
        },
        "internal_handler_http.UpdateNotificationPreferencesRequest": {
            "type": "object",
            "properties": {
                "calls": {
                    "type": "boolean",
                    "example": false
                },
                "direct_messages": {
                    "type": "boolean",
                    "example": false
                },
                "friend_requests": {
                    "type": "boolean",
                    "example": true
                },
                "group_messages": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_handler_http.UserListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler_http.UserResponse"
                    }
                },
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "next_cursor": {
                    "type": "string",
                    "example": "eyJpZCI6IjAxOTJmNWEzLTdjMWItN2EzZi05YjFjLTJkM2U0ZjVhNmI3YyIsInRzIjoiMjAyNi0wNS0wMlQwOTozMToyMS44MTBaIn0="
                }
            }
        },
        "internal_handler_http.UserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://wakeup.app/avatars/caden.png"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-02T09:31:21.810Z"
                },
                "display_name": {
                    "type": "string",
                    "example": "Caden Lund"
                },
                "id": {
                    "type": "string",
                    "example": "0192f5a3-7c1b-7a3f-9b1c-2d3e4f5a6b7c"
                },
                "username": {
                    "type": "string",
                    "example": "caden"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "wakeup_session",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Wakeup API",
	Description:      "Friend-graph chat backend. See docs/WAKEUP.md for the full spec.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
