/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export type GetV1SearchParams = {
/**
 * Search query (min 2 chars)
 */
q: string;
/**
 * Comma-joined sections to include
 */
types?: string;
};
