/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export type GetV1AdminUsersParams = {
/**
 * Search prefix
 */
q?: string;
/**
 * Page size (default 20, max 100)
 */
limit?: number;
/**
 * Opaque pagination cursor
 */
cursor?: string;
};
