/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpPasswordResetConfirmRequest {
  /**
     * @minLength 8
     * @maxLength 128
     */
  new_password: string;
  /**
     * @minLength 1
     * @maxLength 512
     */
  token: string;
}
