/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpImpersonatorInfo } from './internalHandlerHttpImpersonatorInfo';

export interface InternalHandlerHttpMeResponse {
  avatar_url?: string;
  bio?: string;
  color_scheme?: string;
  created_at?: string;
  display_name?: string;
  email?: string;
  id?: string;
  impersonated_by?: InternalHandlerHttpImpersonatorInfo;
  /** OnboardedAt is null until the user finishes the post-login
  onboarding carousel. The mobile AuthGate (WAKEUPEXPO §3.0)
  routes to (onboarding) while this is null so a fresh sign-in
  on a new device doesn't re-onboard a user who already finished. */
  onboarded_at?: string;
  role?: string;
  status_emoji?: string;
  username?: string;
}
