/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpImpersonatorInfo } from './internalHandlerHttpImpersonatorInfo';

export interface InternalHandlerHttpMeResponse {
  avatar_url?: string;
  bio?: string;
  color_scheme?: string;
  created_at?: string;
  display_name?: string;
  email?: string;
  id?: string;
  impersonated_by?: InternalHandlerHttpImpersonatorInfo;
  role?: string;
  status_emoji?: string;
  username?: string;
}
