/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpUserResponse {
  avatar_url?: string;
  bio?: string;
  created_at?: string;
  display_name?: string;
  id?: string;
  status_emoji?: string;
  username?: string;
}
