/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export type InternalHandlerHttpUpdateNotificationPreferencesRequestThemeScheme = typeof InternalHandlerHttpUpdateNotificationPreferencesRequestThemeScheme[keyof typeof InternalHandlerHttpUpdateNotificationPreferencesRequestThemeScheme];


export const InternalHandlerHttpUpdateNotificationPreferencesRequestThemeScheme = {
  system: 'system',
  sunrise: 'sunrise',
  daylight: 'daylight',
  noon: 'noon',
  golden: 'golden',
  meadow: 'meadow',
  dusk: 'dusk',
  twilight: 'twilight',
  aurora: 'aurora',
  midnight: 'midnight',
  rem: 'rem',
} as const;
