/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpUserResponse } from './internalHandlerHttpUserResponse';

export interface InternalHandlerHttpFriendshipResponse {
  accepted_at?: string;
  created_at?: string;
  id?: string;
  status?: string;
  user?: InternalHandlerHttpUserResponse;
}
