/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpAdminUserResponse {
  avatar_url?: string;
  created_at?: string;
  deleted_at?: string;
  display_name?: string;
  email?: string;
  id?: string;
  role?: string;
  username?: string;
}
