/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpUpdateAdminUserRequestRole } from './internalHandlerHttpUpdateAdminUserRequestRole';

export interface InternalHandlerHttpUpdateAdminUserRequest {
  deleted_at?: string;
  role?: InternalHandlerHttpUpdateAdminUserRequestRole;
}
