/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpSendMessageRequest {
  /** @maxItems 10 */
  attachment_ids?: string[];
  /**
     * @minLength 1
     * @maxLength 10000
     */
  body: string;
  reply_to_message_id?: string;
}
