/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpLoginRequest {
  /**
     * @minLength 3
     * @maxLength 254
     */
  identifier: string;
  /**
     * @minLength 1
     * @maxLength 128
     */
  password: string;
}
