/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpUpdateNotificationPreferencesRequestThemeModePreference } from './internalHandlerHttpUpdateNotificationPreferencesRequestThemeModePreference';
import type { InternalHandlerHttpUpdateNotificationPreferencesRequestThemeScheme } from './internalHandlerHttpUpdateNotificationPreferencesRequestThemeScheme';

export interface InternalHandlerHttpUpdateNotificationPreferencesRequest {
  calls?: boolean;
  direct_messages?: boolean;
  friend_requests?: boolean;
  group_messages?: boolean;
  theme_mode_preference?: InternalHandlerHttpUpdateNotificationPreferencesRequestThemeModePreference;
  theme_scheme?: InternalHandlerHttpUpdateNotificationPreferencesRequestThemeScheme;
}
