/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpUpdateConversationRequest {
  /** @maxLength 2048 */
  avatar_url?: string;
  /**
     * @minLength 1
     * @maxLength 80
     */
  name?: string;
}
