/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpSearchConversationRow } from './internalHandlerHttpSearchConversationRow';
import type { InternalHandlerHttpSearchMessageRow } from './internalHandlerHttpSearchMessageRow';
import type { InternalHandlerHttpUserResponse } from './internalHandlerHttpUserResponse';

export interface InternalHandlerHttpSearchResponse {
  conversations?: InternalHandlerHttpSearchConversationRow[];
  conversations_total?: number;
  messages?: InternalHandlerHttpSearchMessageRow[];
  messages_total?: number;
  users?: InternalHandlerHttpUserResponse[];
  users_total?: number;
}
