/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpConversationMemberRow } from './internalHandlerHttpConversationMemberRow';

export interface InternalHandlerHttpConversationResponse {
  avatar_url?: string;
  created_at?: string;
  id?: string;
  last_message_at?: string;
  members?: InternalHandlerHttpConversationMemberRow[];
  /** MutedUntil + PinnedAt are the CALLER's membership state, not
  shared. Other members may have different mute / pin values for
  the same conversation. Surfaced here so the list and detail
  responses give the client everything it needs to render mute
  icons and sort pinned-first without follow-up calls. */
  muted_until?: string;
  name?: string;
  pinned_at?: string;
  type?: string;
  updated_at?: string;
}
