/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export type InternalHandlerHttpUpdateNotificationPreferencesRequestThemeModePreference = typeof InternalHandlerHttpUpdateNotificationPreferencesRequestThemeModePreference[keyof typeof InternalHandlerHttpUpdateNotificationPreferencesRequestThemeModePreference];


export const InternalHandlerHttpUpdateNotificationPreferencesRequestThemeModePreference = {
  system: 'system',
  light: 'light',
  dark: 'dark',
} as const;
