/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpContactsMatchRequest {
  /**
     * EmailHashes is a slice of lowercase hex SHA-256 strings (exactly
  64 chars each). Cap: 1000 entries — chunk client-side past that.
  Length check at the validator; lowercase-hex check at the service
  (regex `/^[0-9a-f]{64}$/`). Two passes keep the malformed-input
  error path typed (Validation, not Internal).
     * @minItems 1
     * @maxItems 1000
     */
  email_hashes: string[];
}
