/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export type InternalHandlerHttpUpdateMeRequestColorScheme = typeof InternalHandlerHttpUpdateMeRequestColorScheme[keyof typeof InternalHandlerHttpUpdateMeRequestColorScheme];


export const InternalHandlerHttpUpdateMeRequestColorScheme = {
  light: 'light',
  dark: 'dark',
  system: 'system',
} as const;
