/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpAdminUserResponse } from './internalHandlerHttpAdminUserResponse';

export interface InternalHandlerHttpAdminUserListResponse {
  data?: InternalHandlerHttpAdminUserResponse[];
  has_more?: boolean;
  next_cursor?: string;
}
