/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpUpdateMeRequestColorScheme } from './internalHandlerHttpUpdateMeRequestColorScheme';

export interface InternalHandlerHttpUpdateMeRequest {
  /** @maxLength 2048 */
  avatar_url?: string;
  /** @maxLength 280 */
  bio?: string;
  color_scheme?: InternalHandlerHttpUpdateMeRequestColorScheme;
  /**
     * @minLength 1
     * @maxLength 64
     */
  display_name?: string;
  /** @maxLength 8 */
  status_emoji?: string;
}
