/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export type InternalHandlerHttpSetPresenceStatusRequestStatus = typeof InternalHandlerHttpSetPresenceStatusRequestStatus[keyof typeof InternalHandlerHttpSetPresenceStatusRequestStatus];


export const InternalHandlerHttpSetPresenceStatusRequestStatus = {
  online: 'online',
  away: 'away',
  sleeping: 'sleeping',
  dnd: 'dnd',
} as const;
