/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpConversationMemberRow } from './internalHandlerHttpConversationMemberRow';
import type { InternalHandlerHttpMessagePreview } from './internalHandlerHttpMessagePreview';

export interface InternalHandlerHttpConversationResponse {
  avatar_url?: string;
  created_at?: string;
  id?: string;
  /** LastMessage is a preview of the most recent message in the
  conversation — the chats list (and global search) renders the
  row's subtitle from it ("You: hey" / "Ada: hey" / "Message
  deleted"). JSON-null (not omitted) when the conversation has no
  messages yet — stable nullability so clients can tell "empty
  conversation" from "older response without the field". */
  last_message?: InternalHandlerHttpMessagePreview;
  last_message_at?: string;
  members?: InternalHandlerHttpConversationMemberRow[];
  /** MutedUntil + PinnedAt are the CALLER's membership state, not
  shared. Other members may have different mute / pin values for
  the same conversation. Surfaced here so the list and detail
  responses give the client everything it needs to render mute
  icons and sort pinned-first without follow-up calls. */
  muted_until?: string;
  name?: string;
  pinned_at?: string;
  type?: string;
  /** UnreadCount is the number of messages in this conversation the
  caller hasn't read yet — same definition as the X-Unread-Total
  header (excludes the caller's own messages + soft-deleted ones,
  counts everything after the caller's last_read pointer). Mobile
  renders the per-row unread badge from this. Best-effort: 0 when
  the count can't be computed (graceful degradation), so clients
  should treat it as a hint, not a guarantee. */
  unread_count?: number;
  updated_at?: string;
}
