/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpRegisterRequest {
  /**
     * @minLength 1
     * @maxLength 64
     */
  display_name: string;
  /** @maxLength 254 */
  email: string;
  /**
     * @minLength 8
     * @maxLength 128
     */
  password: string;
  /**
     * @minLength 3
     * @maxLength 32
     */
  username: string;
}
