/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export type InternalHandlerHttpCreateConversationRequestType = typeof InternalHandlerHttpCreateConversationRequestType[keyof typeof InternalHandlerHttpCreateConversationRequestType];


export const InternalHandlerHttpCreateConversationRequestType = {
  direct: 'direct',
  group: 'group',
} as const;
