/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpConversationMemberResponse {
  conversation_id?: string;
  joined_at?: string;
  last_read_message_id?: string;
  muted_until?: string;
  pinned_at?: string;
  role?: string;
  user_id?: string;
}
