/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */

export interface InternalHandlerHttpVoIPTokenResponse {
  created_at?: string;
  id?: string;
  last_seen_at?: string;
  voip_token?: string;
}
