/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import type { InternalHandlerHttpAuditLogResponseMetadata } from './internalHandlerHttpAuditLogResponseMetadata';

export interface InternalHandlerHttpAuditLogResponse {
  action?: string;
  actor_id?: string;
  created_at?: string;
  id?: string;
  metadata?: InternalHandlerHttpAuditLogResponseMetadata;
  target_id?: string;
  target_type?: string;
}
