/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalHandlerHttpAttachmentResponse,
  InternalHandlerHttpErrorResponse,
  PostV1AttachmentsBody
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postV1AttachmentsResponse201 = {
  data: InternalHandlerHttpAttachmentResponse
  status: 201
}

export type postV1AttachmentsResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1AttachmentsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1AttachmentsResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1AttachmentsResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1AttachmentsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AttachmentsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AttachmentsResponseSuccess = (postV1AttachmentsResponse201) & {
  headers: Headers;
};
export type postV1AttachmentsResponseError = (postV1AttachmentsResponse400 | postV1AttachmentsResponse401 | postV1AttachmentsResponse413 | postV1AttachmentsResponse422 | postV1AttachmentsResponse429 | postV1AttachmentsResponse500) & {
  headers: Headers;
};

export type postV1AttachmentsResponse = (postV1AttachmentsResponseSuccess | postV1AttachmentsResponseError)

export const getPostV1AttachmentsUrl = () => {




  return `/v1/attachments`
}

/**
 * Accepts a multipart form with a single `file` field. Max 50 MiB; the server detects the MIME from the first 512 bytes (§9.2) — the client-supplied content-type and filename extension are ignored for type-checking purposes. Allowed types: image/png, image/jpeg, image/gif, image/webp, application/pdf, text/plain. The response includes a 5-minute presigned URL so the uploader can render the attachment without a follow-up GET.
 * @summary Upload an attachment
 */
export const postV1Attachments = async (postV1AttachmentsBody: PostV1AttachmentsBody, options?: RequestInit): Promise<postV1AttachmentsResponse> => {
    const formData = new FormData();
formData.append(`file`, postV1AttachmentsBody.file);

  return orvalMutator<postV1AttachmentsResponse>(getPostV1AttachmentsUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getPostV1AttachmentsMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Attachments>>, TError,{data: PostV1AttachmentsBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1Attachments>>, TError,{data: PostV1AttachmentsBody}, TContext> => {

const mutationKey = ['postV1Attachments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1Attachments>>, {data: PostV1AttachmentsBody}> = (props) => {
          const {data} = props ?? {};

          return  postV1Attachments(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AttachmentsMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Attachments>>>
    export type PostV1AttachmentsMutationBody = PostV1AttachmentsBody
    export type PostV1AttachmentsMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Upload an attachment
 */
export const usePostV1Attachments = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Attachments>>, TError,{data: PostV1AttachmentsBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1Attachments>>,
        TError,
        {data: PostV1AttachmentsBody},
        TContext
      > => {
      return useMutation(getPostV1AttachmentsMutationOptions(options), queryClient);
    }
    export type getV1AttachmentsIdResponse200 = {
  data: InternalHandlerHttpAttachmentResponse
  status: 200
}

export type getV1AttachmentsIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1AttachmentsIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1AttachmentsIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getV1AttachmentsIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1AttachmentsIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1AttachmentsIdResponseSuccess = (getV1AttachmentsIdResponse200) & {
  headers: Headers;
};
export type getV1AttachmentsIdResponseError = (getV1AttachmentsIdResponse400 | getV1AttachmentsIdResponse401 | getV1AttachmentsIdResponse404 | getV1AttachmentsIdResponse429 | getV1AttachmentsIdResponse500) & {
  headers: Headers;
};

export type getV1AttachmentsIdResponse = (getV1AttachmentsIdResponseSuccess | getV1AttachmentsIdResponseError)

export const getGetV1AttachmentsIdUrl = (id: string,) => {




  return `/v1/attachments/${id}`
}

/**
 * Returns metadata + a 5-minute presigned download URL. Membership-gated per §9.3 — the caller must be a member of a conversation containing a message linked to this attachment, OR the uploader of an attachment that has not yet been linked to any message. Any failure (missing or unauthorized) returns 404 — never 403, never leaks existence.
 * @summary Get attachment with presigned URL
 */
export const getV1AttachmentsId = async (id: string, options?: RequestInit): Promise<getV1AttachmentsIdResponse> => {

  return orvalMutator<getV1AttachmentsIdResponse>(getGetV1AttachmentsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1AttachmentsIdQueryKey = (id: string,) => {
    return [
    `/v1/attachments/${id}`
    ] as const;
    }


export const getGetV1AttachmentsIdQueryOptions = <TData = Awaited<ReturnType<typeof getV1AttachmentsId>>, TError = InternalHandlerHttpErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AttachmentsId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1AttachmentsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1AttachmentsId>>> = ({ signal }) => getV1AttachmentsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1AttachmentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1AttachmentsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getV1AttachmentsId>>>
export type GetV1AttachmentsIdQueryError = InternalHandlerHttpErrorResponse


export function useGetV1AttachmentsId<TData = Awaited<ReturnType<typeof getV1AttachmentsId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AttachmentsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AttachmentsId>>,
          TError,
          Awaited<ReturnType<typeof getV1AttachmentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AttachmentsId<TData = Awaited<ReturnType<typeof getV1AttachmentsId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AttachmentsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AttachmentsId>>,
          TError,
          Awaited<ReturnType<typeof getV1AttachmentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AttachmentsId<TData = Awaited<ReturnType<typeof getV1AttachmentsId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AttachmentsId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get attachment with presigned URL
 */

export function useGetV1AttachmentsId<TData = Awaited<ReturnType<typeof getV1AttachmentsId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AttachmentsId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1AttachmentsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






