/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1ConversationsParams,
  InternalHandlerHttpAddMembersRequest,
  InternalHandlerHttpAddMembersResponse,
  InternalHandlerHttpConversationListResponse,
  InternalHandlerHttpConversationMemberResponse,
  InternalHandlerHttpConversationResponse,
  InternalHandlerHttpCreateConversationRequest,
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpMarkReadRequest,
  InternalHandlerHttpSetMuteRequest,
  InternalHandlerHttpSetPinRequest,
  InternalHandlerHttpUpdateConversationRequest
} from '../../model';

import { orvalMutator } from '../../orval-mutator';




export type getV1ConversationsResponse200 = {
  data: InternalHandlerHttpConversationListResponse
  status: 200
}

export type getV1ConversationsResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1ConversationsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1ConversationsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1ConversationsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1ConversationsResponseSuccess = (getV1ConversationsResponse200) & {
  headers: Headers;
};
export type getV1ConversationsResponseError = (getV1ConversationsResponse400 | getV1ConversationsResponse401 | getV1ConversationsResponse429 | getV1ConversationsResponse500) & {
  headers: Headers;
};

export type getV1ConversationsResponse = (getV1ConversationsResponseSuccess | getV1ConversationsResponseError)

export const getGetV1ConversationsUrl = (params?: GetV1ConversationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/conversations?${stringifiedParams}` : `/v1/conversations`
}

/**
 * Returns the caller's conversations keyset-paginated by `last_message_at DESC, id DESC` per §6.4. Each row embeds the full member list with public profiles.
 * @summary List conversations
 */
export const getV1Conversations = async (params?: GetV1ConversationsParams, options?: RequestInit): Promise<getV1ConversationsResponse> => {

  return orvalMutator<getV1ConversationsResponse>(getGetV1ConversationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1ConversationsQueryKey = (params?: GetV1ConversationsParams,) => {
    return [
    `/v1/conversations`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1ConversationsQueryOptions = <TData = Awaited<ReturnType<typeof getV1Conversations>>, TError = InternalHandlerHttpErrorResponse>(params?: GetV1ConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Conversations>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1ConversationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Conversations>>> = ({ signal }) => getV1Conversations(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Conversations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1ConversationsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Conversations>>>
export type GetV1ConversationsQueryError = InternalHandlerHttpErrorResponse


export function useGetV1Conversations<TData = Awaited<ReturnType<typeof getV1Conversations>>, TError = InternalHandlerHttpErrorResponse>(
 params: undefined |  GetV1ConversationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Conversations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Conversations>>,
          TError,
          Awaited<ReturnType<typeof getV1Conversations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Conversations<TData = Awaited<ReturnType<typeof getV1Conversations>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1ConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Conversations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Conversations>>,
          TError,
          Awaited<ReturnType<typeof getV1Conversations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Conversations<TData = Awaited<ReturnType<typeof getV1Conversations>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1ConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Conversations>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List conversations
 */

export function useGetV1Conversations<TData = Awaited<ReturnType<typeof getV1Conversations>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1ConversationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Conversations>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1ConversationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1ConversationsResponse201 = {
  data: InternalHandlerHttpConversationResponse
  status: 201
}

export type postV1ConversationsResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1ConversationsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1ConversationsResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1ConversationsResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type postV1ConversationsResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1ConversationsResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1ConversationsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1ConversationsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1ConversationsResponseSuccess = (postV1ConversationsResponse201) & {
  headers: Headers;
};
export type postV1ConversationsResponseError = (postV1ConversationsResponse400 | postV1ConversationsResponse401 | postV1ConversationsResponse404 | postV1ConversationsResponse409 | postV1ConversationsResponse413 | postV1ConversationsResponse422 | postV1ConversationsResponse429 | postV1ConversationsResponse500) & {
  headers: Headers;
};

export type postV1ConversationsResponse = (postV1ConversationsResponseSuccess | postV1ConversationsResponseError)

export const getPostV1ConversationsUrl = () => {




  return `/v1/conversations`
}

/**
 * Creates a direct (`type=direct`, exactly 1 entry in `member_ids`) or group (`type=group`, 1-24 entries in `member_ids` + `name` required). Direct creation deduplicates: if a direct between the same pair already exists, the existing row is returned with 201.
 * @summary Create a conversation
 */
export const postV1Conversations = async (internalHandlerHttpCreateConversationRequest: InternalHandlerHttpCreateConversationRequest, options?: RequestInit): Promise<postV1ConversationsResponse> => {

  return orvalMutator<postV1ConversationsResponse>(getPostV1ConversationsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpCreateConversationRequest,)
  }
);}




export const getPostV1ConversationsMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Conversations>>, TError,{data: InternalHandlerHttpCreateConversationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1Conversations>>, TError,{data: InternalHandlerHttpCreateConversationRequest}, TContext> => {

const mutationKey = ['postV1Conversations'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1Conversations>>, {data: InternalHandlerHttpCreateConversationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1Conversations(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ConversationsMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Conversations>>>
    export type PostV1ConversationsMutationBody = InternalHandlerHttpCreateConversationRequest
    export type PostV1ConversationsMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Create a conversation
 */
export const usePostV1Conversations = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Conversations>>, TError,{data: InternalHandlerHttpCreateConversationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1Conversations>>,
        TError,
        {data: InternalHandlerHttpCreateConversationRequest},
        TContext
      > => {
      return useMutation(getPostV1ConversationsMutationOptions(options), queryClient);
    }
    export type getV1ConversationsIdResponse200 = {
  data: InternalHandlerHttpConversationResponse
  status: 200
}

export type getV1ConversationsIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1ConversationsIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1ConversationsIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getV1ConversationsIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1ConversationsIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1ConversationsIdResponseSuccess = (getV1ConversationsIdResponse200) & {
  headers: Headers;
};
export type getV1ConversationsIdResponseError = (getV1ConversationsIdResponse400 | getV1ConversationsIdResponse401 | getV1ConversationsIdResponse404 | getV1ConversationsIdResponse429 | getV1ConversationsIdResponse500) & {
  headers: Headers;
};

export type getV1ConversationsIdResponse = (getV1ConversationsIdResponseSuccess | getV1ConversationsIdResponseError)

export const getGetV1ConversationsIdUrl = (id: string,) => {




  return `/v1/conversations/${id}`
}

/**
 * Returns the conversation row with its full member list. Caller must be a member; non-members surface as 404 so the existence of the conversation isn't leaked across the friend graph.
 * @summary Get conversation
 */
export const getV1ConversationsId = async (id: string, options?: RequestInit): Promise<getV1ConversationsIdResponse> => {

  return orvalMutator<getV1ConversationsIdResponse>(getGetV1ConversationsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1ConversationsIdQueryKey = (id: string,) => {
    return [
    `/v1/conversations/${id}`
    ] as const;
    }


export const getGetV1ConversationsIdQueryOptions = <TData = Awaited<ReturnType<typeof getV1ConversationsId>>, TError = InternalHandlerHttpErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1ConversationsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1ConversationsId>>> = ({ signal }) => getV1ConversationsId(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1ConversationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getV1ConversationsId>>>
export type GetV1ConversationsIdQueryError = InternalHandlerHttpErrorResponse


export function useGetV1ConversationsId<TData = Awaited<ReturnType<typeof getV1ConversationsId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1ConversationsId>>,
          TError,
          Awaited<ReturnType<typeof getV1ConversationsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1ConversationsId<TData = Awaited<ReturnType<typeof getV1ConversationsId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1ConversationsId>>,
          TError,
          Awaited<ReturnType<typeof getV1ConversationsId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1ConversationsId<TData = Awaited<ReturnType<typeof getV1ConversationsId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get conversation
 */

export function useGetV1ConversationsId<TData = Awaited<ReturnType<typeof getV1ConversationsId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsId>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1ConversationsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteV1ConversationsIdResponse204 = {
  data: void
  status: 204
}

export type deleteV1ConversationsIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type deleteV1ConversationsIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1ConversationsIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type deleteV1ConversationsIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1ConversationsIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1ConversationsIdResponseSuccess = (deleteV1ConversationsIdResponse204) & {
  headers: Headers;
};
export type deleteV1ConversationsIdResponseError = (deleteV1ConversationsIdResponse400 | deleteV1ConversationsIdResponse401 | deleteV1ConversationsIdResponse404 | deleteV1ConversationsIdResponse429 | deleteV1ConversationsIdResponse500) & {
  headers: Headers;
};

export type deleteV1ConversationsIdResponse = (deleteV1ConversationsIdResponseSuccess | deleteV1ConversationsIdResponseError)

export const getDeleteV1ConversationsIdUrl = (id: string,) => {




  return `/v1/conversations/${id}`
}

/**
 * Removes the caller's membership. For groups this is "leave"; for directs it acts as "hide" — the other party still sees the conversation.
 * @summary Leave a conversation
 */
export const deleteV1ConversationsId = async (id: string, options?: RequestInit): Promise<deleteV1ConversationsIdResponse> => {

  return orvalMutator<deleteV1ConversationsIdResponse>(getDeleteV1ConversationsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1ConversationsIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1ConversationsId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1ConversationsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteV1ConversationsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1ConversationsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteV1ConversationsId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1ConversationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1ConversationsId>>>

    export type DeleteV1ConversationsIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Leave a conversation
 */
export const useDeleteV1ConversationsId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1ConversationsId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1ConversationsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteV1ConversationsIdMutationOptions(options), queryClient);
    }
    export type patchV1ConversationsIdResponse200 = {
  data: InternalHandlerHttpConversationResponse
  status: 200
}

export type patchV1ConversationsIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type patchV1ConversationsIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type patchV1ConversationsIdResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type patchV1ConversationsIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type patchV1ConversationsIdResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type patchV1ConversationsIdResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type patchV1ConversationsIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type patchV1ConversationsIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type patchV1ConversationsIdResponseSuccess = (patchV1ConversationsIdResponse200) & {
  headers: Headers;
};
export type patchV1ConversationsIdResponseError = (patchV1ConversationsIdResponse400 | patchV1ConversationsIdResponse401 | patchV1ConversationsIdResponse403 | patchV1ConversationsIdResponse404 | patchV1ConversationsIdResponse413 | patchV1ConversationsIdResponse422 | patchV1ConversationsIdResponse429 | patchV1ConversationsIdResponse500) & {
  headers: Headers;
};

export type patchV1ConversationsIdResponse = (patchV1ConversationsIdResponseSuccess | patchV1ConversationsIdResponseError)

export const getPatchV1ConversationsIdUrl = (id: string,) => {




  return `/v1/conversations/${id}`
}

/**
 * Patches name / avatar_url. Caller must be an admin of the conversation. Direct conversations are immutable. Non-members get 404 — no enumeration.
 * @summary Update conversation (group only)
 */
export const patchV1ConversationsId = async (id: string,
    internalHandlerHttpUpdateConversationRequest: InternalHandlerHttpUpdateConversationRequest, options?: RequestInit): Promise<patchV1ConversationsIdResponse> => {

  return orvalMutator<patchV1ConversationsIdResponse>(getPatchV1ConversationsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpUpdateConversationRequest,)
  }
);}




export const getPatchV1ConversationsIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsId>>, TError,{id: string;data: InternalHandlerHttpUpdateConversationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsId>>, TError,{id: string;data: InternalHandlerHttpUpdateConversationRequest}, TContext> => {

const mutationKey = ['patchV1ConversationsId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchV1ConversationsId>>, {id: string;data: InternalHandlerHttpUpdateConversationRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchV1ConversationsId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchV1ConversationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchV1ConversationsId>>>
    export type PatchV1ConversationsIdMutationBody = InternalHandlerHttpUpdateConversationRequest
    export type PatchV1ConversationsIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Update conversation (group only)
 */
export const usePatchV1ConversationsId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsId>>, TError,{id: string;data: InternalHandlerHttpUpdateConversationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchV1ConversationsId>>,
        TError,
        {id: string;data: InternalHandlerHttpUpdateConversationRequest},
        TContext
      > => {
      return useMutation(getPatchV1ConversationsIdMutationOptions(options), queryClient);
    }
    export type postV1ConversationsIdMembersResponse200 = {
  data: InternalHandlerHttpAddMembersResponse
  status: 200
}

export type postV1ConversationsIdMembersResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1ConversationsIdMembersResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1ConversationsIdMembersResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type postV1ConversationsIdMembersResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1ConversationsIdMembersResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type postV1ConversationsIdMembersResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1ConversationsIdMembersResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1ConversationsIdMembersResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1ConversationsIdMembersResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1ConversationsIdMembersResponseSuccess = (postV1ConversationsIdMembersResponse200) & {
  headers: Headers;
};
export type postV1ConversationsIdMembersResponseError = (postV1ConversationsIdMembersResponse400 | postV1ConversationsIdMembersResponse401 | postV1ConversationsIdMembersResponse403 | postV1ConversationsIdMembersResponse404 | postV1ConversationsIdMembersResponse409 | postV1ConversationsIdMembersResponse413 | postV1ConversationsIdMembersResponse422 | postV1ConversationsIdMembersResponse429 | postV1ConversationsIdMembersResponse500) & {
  headers: Headers;
};

export type postV1ConversationsIdMembersResponse = (postV1ConversationsIdMembersResponseSuccess | postV1ConversationsIdMembersResponseError)

export const getPostV1ConversationsIdMembersUrl = (id: string,) => {




  return `/v1/conversations/${id}/members`
}

/**
 * Admin-only. Each invitee is checked against the §4.6 cap-25; the request errors with 409 the moment the cap is hit. Direct conversations don't accept members.
 * @summary Add members to a group
 */
export const postV1ConversationsIdMembers = async (id: string,
    internalHandlerHttpAddMembersRequest: InternalHandlerHttpAddMembersRequest, options?: RequestInit): Promise<postV1ConversationsIdMembersResponse> => {

  return orvalMutator<postV1ConversationsIdMembersResponse>(getPostV1ConversationsIdMembersUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpAddMembersRequest,)
  }
);}




export const getPostV1ConversationsIdMembersMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdMembers>>, TError,{id: string;data: InternalHandlerHttpAddMembersRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdMembers>>, TError,{id: string;data: InternalHandlerHttpAddMembersRequest}, TContext> => {

const mutationKey = ['postV1ConversationsIdMembers'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1ConversationsIdMembers>>, {id: string;data: InternalHandlerHttpAddMembersRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1ConversationsIdMembers(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ConversationsIdMembersMutationResult = NonNullable<Awaited<ReturnType<typeof postV1ConversationsIdMembers>>>
    export type PostV1ConversationsIdMembersMutationBody = InternalHandlerHttpAddMembersRequest
    export type PostV1ConversationsIdMembersMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Add members to a group
 */
export const usePostV1ConversationsIdMembers = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdMembers>>, TError,{id: string;data: InternalHandlerHttpAddMembersRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1ConversationsIdMembers>>,
        TError,
        {id: string;data: InternalHandlerHttpAddMembersRequest},
        TContext
      > => {
      return useMutation(getPostV1ConversationsIdMembersMutationOptions(options), queryClient);
    }
    export type deleteV1ConversationsIdMembersUserIdResponse204 = {
  data: void
  status: 204
}

export type deleteV1ConversationsIdMembersUserIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type deleteV1ConversationsIdMembersUserIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1ConversationsIdMembersUserIdResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type deleteV1ConversationsIdMembersUserIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type deleteV1ConversationsIdMembersUserIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1ConversationsIdMembersUserIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1ConversationsIdMembersUserIdResponseSuccess = (deleteV1ConversationsIdMembersUserIdResponse204) & {
  headers: Headers;
};
export type deleteV1ConversationsIdMembersUserIdResponseError = (deleteV1ConversationsIdMembersUserIdResponse400 | deleteV1ConversationsIdMembersUserIdResponse401 | deleteV1ConversationsIdMembersUserIdResponse403 | deleteV1ConversationsIdMembersUserIdResponse404 | deleteV1ConversationsIdMembersUserIdResponse429 | deleteV1ConversationsIdMembersUserIdResponse500) & {
  headers: Headers;
};

export type deleteV1ConversationsIdMembersUserIdResponse = (deleteV1ConversationsIdMembersUserIdResponseSuccess | deleteV1ConversationsIdMembersUserIdResponseError)

export const getDeleteV1ConversationsIdMembersUserIdUrl = (id: string,
    userId: string,) => {




  return `/v1/conversations/${id}/members/${userId}`
}

/**
 * Removes a member from the conversation. Self-removal is always allowed (acts as Leave). Removing another user requires admin role on a group.
 * @summary Remove a member
 */
export const deleteV1ConversationsIdMembersUserId = async (id: string,
    userId: string, options?: RequestInit): Promise<deleteV1ConversationsIdMembersUserIdResponse> => {

  return orvalMutator<deleteV1ConversationsIdMembersUserIdResponse>(getDeleteV1ConversationsIdMembersUserIdUrl(id,userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1ConversationsIdMembersUserIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1ConversationsIdMembersUserId>>, TError,{id: string;userId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1ConversationsIdMembersUserId>>, TError,{id: string;userId: string}, TContext> => {

const mutationKey = ['deleteV1ConversationsIdMembersUserId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1ConversationsIdMembersUserId>>, {id: string;userId: string}> = (props) => {
          const {id,userId} = props ?? {};

          return  deleteV1ConversationsIdMembersUserId(id,userId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1ConversationsIdMembersUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1ConversationsIdMembersUserId>>>

    export type DeleteV1ConversationsIdMembersUserIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Remove a member
 */
export const useDeleteV1ConversationsIdMembersUserId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1ConversationsIdMembersUserId>>, TError,{id: string;userId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1ConversationsIdMembersUserId>>,
        TError,
        {id: string;userId: string},
        TContext
      > => {
      return useMutation(getDeleteV1ConversationsIdMembersUserIdMutationOptions(options), queryClient);
    }
    export type patchV1ConversationsIdMuteResponse200 = {
  data: InternalHandlerHttpConversationMemberResponse
  status: 200
}

export type patchV1ConversationsIdMuteResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type patchV1ConversationsIdMuteResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type patchV1ConversationsIdMuteResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type patchV1ConversationsIdMuteResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type patchV1ConversationsIdMuteResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type patchV1ConversationsIdMuteResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type patchV1ConversationsIdMuteResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type patchV1ConversationsIdMuteResponseSuccess = (patchV1ConversationsIdMuteResponse200) & {
  headers: Headers;
};
export type patchV1ConversationsIdMuteResponseError = (patchV1ConversationsIdMuteResponse400 | patchV1ConversationsIdMuteResponse401 | patchV1ConversationsIdMuteResponse404 | patchV1ConversationsIdMuteResponse413 | patchV1ConversationsIdMuteResponse422 | patchV1ConversationsIdMuteResponse429 | patchV1ConversationsIdMuteResponse500) & {
  headers: Headers;
};

export type patchV1ConversationsIdMuteResponse = (patchV1ConversationsIdMuteResponseSuccess | patchV1ConversationsIdMuteResponseError)

export const getPatchV1ConversationsIdMuteUrl = (id: string,) => {




  return `/v1/conversations/${id}/mute`
}

/**
 * Per-member toggle. Body: `{ "until": ISO8601 timestamp | null }`. `null` unmutes; a future timestamp suppresses pushes until then; "forever" is just a far-future stamp like `2099-01-01T00:00:00Z`. WS events still fire — only the push-fanout is gated. Non-members get 404.
 * @summary Mute / unmute a conversation
 */
export const patchV1ConversationsIdMute = async (id: string,
    internalHandlerHttpSetMuteRequest: InternalHandlerHttpSetMuteRequest, options?: RequestInit): Promise<patchV1ConversationsIdMuteResponse> => {

  return orvalMutator<patchV1ConversationsIdMuteResponse>(getPatchV1ConversationsIdMuteUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpSetMuteRequest,)
  }
);}




export const getPatchV1ConversationsIdMuteMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsIdMute>>, TError,{id: string;data: InternalHandlerHttpSetMuteRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsIdMute>>, TError,{id: string;data: InternalHandlerHttpSetMuteRequest}, TContext> => {

const mutationKey = ['patchV1ConversationsIdMute'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchV1ConversationsIdMute>>, {id: string;data: InternalHandlerHttpSetMuteRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchV1ConversationsIdMute(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchV1ConversationsIdMuteMutationResult = NonNullable<Awaited<ReturnType<typeof patchV1ConversationsIdMute>>>
    export type PatchV1ConversationsIdMuteMutationBody = InternalHandlerHttpSetMuteRequest
    export type PatchV1ConversationsIdMuteMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Mute / unmute a conversation
 */
export const usePatchV1ConversationsIdMute = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsIdMute>>, TError,{id: string;data: InternalHandlerHttpSetMuteRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchV1ConversationsIdMute>>,
        TError,
        {id: string;data: InternalHandlerHttpSetMuteRequest},
        TContext
      > => {
      return useMutation(getPatchV1ConversationsIdMuteMutationOptions(options), queryClient);
    }
    export type patchV1ConversationsIdPinResponse200 = {
  data: InternalHandlerHttpConversationMemberResponse
  status: 200
}

export type patchV1ConversationsIdPinResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type patchV1ConversationsIdPinResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type patchV1ConversationsIdPinResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type patchV1ConversationsIdPinResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type patchV1ConversationsIdPinResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type patchV1ConversationsIdPinResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type patchV1ConversationsIdPinResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type patchV1ConversationsIdPinResponseSuccess = (patchV1ConversationsIdPinResponse200) & {
  headers: Headers;
};
export type patchV1ConversationsIdPinResponseError = (patchV1ConversationsIdPinResponse400 | patchV1ConversationsIdPinResponse401 | patchV1ConversationsIdPinResponse404 | patchV1ConversationsIdPinResponse413 | patchV1ConversationsIdPinResponse422 | patchV1ConversationsIdPinResponse429 | patchV1ConversationsIdPinResponse500) & {
  headers: Headers;
};

export type patchV1ConversationsIdPinResponse = (patchV1ConversationsIdPinResponseSuccess | patchV1ConversationsIdPinResponseError)

export const getPatchV1ConversationsIdPinUrl = (id: string,) => {




  return `/v1/conversations/${id}/pin`
}

/**
 * Per-member toggle. Body: `{ "pinned": bool }`. The server stamps `pinned_at = now()` when true, NULL when false. Pinning is a UI-ordering hint; the conversation list response includes `pinned_at` so clients can sort pinned-first. Non-members get 404.
 * @summary Pin / unpin a conversation
 */
export const patchV1ConversationsIdPin = async (id: string,
    internalHandlerHttpSetPinRequest: InternalHandlerHttpSetPinRequest, options?: RequestInit): Promise<patchV1ConversationsIdPinResponse> => {

  return orvalMutator<patchV1ConversationsIdPinResponse>(getPatchV1ConversationsIdPinUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpSetPinRequest,)
  }
);}




export const getPatchV1ConversationsIdPinMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsIdPin>>, TError,{id: string;data: InternalHandlerHttpSetPinRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsIdPin>>, TError,{id: string;data: InternalHandlerHttpSetPinRequest}, TContext> => {

const mutationKey = ['patchV1ConversationsIdPin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchV1ConversationsIdPin>>, {id: string;data: InternalHandlerHttpSetPinRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchV1ConversationsIdPin(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchV1ConversationsIdPinMutationResult = NonNullable<Awaited<ReturnType<typeof patchV1ConversationsIdPin>>>
    export type PatchV1ConversationsIdPinMutationBody = InternalHandlerHttpSetPinRequest
    export type PatchV1ConversationsIdPinMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Pin / unpin a conversation
 */
export const usePatchV1ConversationsIdPin = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1ConversationsIdPin>>, TError,{id: string;data: InternalHandlerHttpSetPinRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchV1ConversationsIdPin>>,
        TError,
        {id: string;data: InternalHandlerHttpSetPinRequest},
        TContext
      > => {
      return useMutation(getPatchV1ConversationsIdPinMutationOptions(options), queryClient);
    }
    export type postV1ConversationsIdReadResponse204 = {
  data: void
  status: 204
}

export type postV1ConversationsIdReadResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1ConversationsIdReadResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1ConversationsIdReadResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1ConversationsIdReadResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1ConversationsIdReadResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1ConversationsIdReadResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1ConversationsIdReadResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1ConversationsIdReadResponseSuccess = (postV1ConversationsIdReadResponse204) & {
  headers: Headers;
};
export type postV1ConversationsIdReadResponseError = (postV1ConversationsIdReadResponse400 | postV1ConversationsIdReadResponse401 | postV1ConversationsIdReadResponse404 | postV1ConversationsIdReadResponse413 | postV1ConversationsIdReadResponse422 | postV1ConversationsIdReadResponse429 | postV1ConversationsIdReadResponse500) & {
  headers: Headers;
};

export type postV1ConversationsIdReadResponse = (postV1ConversationsIdReadResponseSuccess | postV1ConversationsIdReadResponseError)

export const getPostV1ConversationsIdReadUrl = (id: string,) => {




  return `/v1/conversations/${id}/read`
}

/**
 * Sets the caller's `last_read_message_id` pointer for the conversation. Frontend uses this to compute unread counts.
 * @summary Mark conversation as read
 */
export const postV1ConversationsIdRead = async (id: string,
    internalHandlerHttpMarkReadRequest: InternalHandlerHttpMarkReadRequest, options?: RequestInit): Promise<postV1ConversationsIdReadResponse> => {

  return orvalMutator<postV1ConversationsIdReadResponse>(getPostV1ConversationsIdReadUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpMarkReadRequest,)
  }
);}




export const getPostV1ConversationsIdReadMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRead>>, TError,{id: string;data: InternalHandlerHttpMarkReadRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRead>>, TError,{id: string;data: InternalHandlerHttpMarkReadRequest}, TContext> => {

const mutationKey = ['postV1ConversationsIdRead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1ConversationsIdRead>>, {id: string;data: InternalHandlerHttpMarkReadRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1ConversationsIdRead(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ConversationsIdReadMutationResult = NonNullable<Awaited<ReturnType<typeof postV1ConversationsIdRead>>>
    export type PostV1ConversationsIdReadMutationBody = InternalHandlerHttpMarkReadRequest
    export type PostV1ConversationsIdReadMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Mark conversation as read
 */
export const usePostV1ConversationsIdRead = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdRead>>, TError,{id: string;data: InternalHandlerHttpMarkReadRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1ConversationsIdRead>>,
        TError,
        {id: string;data: InternalHandlerHttpMarkReadRequest},
        TContext
      > => {
      return useMutation(getPostV1ConversationsIdReadMutationOptions(options), queryClient);
    }
