/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { orvalMutator } from '../../orval-mutator';




export type getV1WsResponse101 = {
  data: void
  status: 101
}

export type getV1WsResponse401 = {
  data: void
  status: 401
}

export type getV1WsResponse429 = {
  data: void
  status: 429
}

export type getV1WsResponse500 = {
  data: void
  status: 500
}

;
export type getV1WsResponseError = (getV1WsResponse101 | getV1WsResponse401 | getV1WsResponse429 | getV1WsResponse500) & {
  headers: Headers;
};

export type getV1WsResponse = (getV1WsResponseError)

export const getGetV1WsUrl = () => {




  return `/v1/ws`
}

/**
 * Upgrades the request to a WebSocket. Auth is enforced before the upgrade via the same session cookie used for REST. The server subscribes the connection to `user:<id>:events` plus `conv:<id>:messages` for every conversation the caller is a member of, and routes inbound `heartbeat` / `typing.*` / `presence.set` events per §7.3. See §7.1 for the JSON envelope format.
 * @summary Open the realtime WebSocket connection
 */
export const getV1Ws = async ( options?: RequestInit): Promise<getV1WsResponse> => {

  return orvalMutator<getV1WsResponse>(getGetV1WsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1WsQueryKey = () => {
    return [
    `/v1/ws`
    ] as const;
    }


export const getGetV1WsQueryOptions = <TData = Awaited<ReturnType<typeof getV1Ws>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Ws>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1WsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Ws>>> = ({ signal }) => getV1Ws({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Ws>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1WsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Ws>>>
export type GetV1WsQueryError = void


export function useGetV1Ws<TData = Awaited<ReturnType<typeof getV1Ws>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Ws>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Ws>>,
          TError,
          Awaited<ReturnType<typeof getV1Ws>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Ws<TData = Awaited<ReturnType<typeof getV1Ws>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Ws>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Ws>>,
          TError,
          Awaited<ReturnType<typeof getV1Ws>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Ws<TData = Awaited<ReturnType<typeof getV1Ws>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Ws>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Open the realtime WebSocket connection
 */

export function useGetV1Ws<TData = Awaited<ReturnType<typeof getV1Ws>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Ws>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1WsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






