/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  InternalHandlerHttpErrorResponse
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postWebhooksLivekitResponse200 = {
  data: void
  status: 200
}

export type postWebhooksLivekitResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postWebhooksLivekitResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postWebhooksLivekitResponseSuccess = (postWebhooksLivekitResponse200) & {
  headers: Headers;
};
export type postWebhooksLivekitResponseError = (postWebhooksLivekitResponse401 | postWebhooksLivekitResponse500) & {
  headers: Headers;
};

export type postWebhooksLivekitResponse = (postWebhooksLivekitResponseSuccess | postWebhooksLivekitResponseError)

export const getPostWebhooksLivekitUrl = () => {




  return `/webhooks/livekit`
}

/**
 * Unauthenticated endpoint that receives LiveKit's room/participant lifecycle events. Signature verification happens inside the handler via the configured KeyProvider — there is no bearer-token / cookie auth here. Events that fail verification get 401; events for unknown rooms get 200 (no enumeration). Handled events: room_started, room_finished, participant_joined, participant_left, track_published (camera only), track_unpublished (camera only).
 * @summary LiveKit webhook receiver
 */
export const postWebhooksLivekit = async ( options?: RequestInit): Promise<postWebhooksLivekitResponse> => {

  return orvalMutator<postWebhooksLivekitResponse>(getPostWebhooksLivekitUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostWebhooksLivekitMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksLivekit>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postWebhooksLivekit>>, TError,void, TContext> => {

const mutationKey = ['postWebhooksLivekit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWebhooksLivekit>>, void> = () => {


          return  postWebhooksLivekit(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostWebhooksLivekitMutationResult = NonNullable<Awaited<ReturnType<typeof postWebhooksLivekit>>>

    export type PostWebhooksLivekitMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary LiveKit webhook receiver
 */
export const usePostWebhooksLivekit = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWebhooksLivekit>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWebhooksLivekit>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostWebhooksLivekitMutationOptions(options), queryClient);
    }
