/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1AdminAuditParams,
  GetV1AdminUsersParams,
  InternalHandlerHttpAdminUserListResponse,
  InternalHandlerHttpAdminUserResponse,
  InternalHandlerHttpAuditLogListResponse,
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpMeResponse,
  InternalHandlerHttpUpdateAdminUserRequest
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getV1AdminAuditResponse200 = {
  data: InternalHandlerHttpAuditLogListResponse
  status: 200
}

export type getV1AdminAuditResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1AdminAuditResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1AdminAuditResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type getV1AdminAuditResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1AdminAuditResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1AdminAuditResponseSuccess = (getV1AdminAuditResponse200) & {
  headers: Headers;
};
export type getV1AdminAuditResponseError = (getV1AdminAuditResponse400 | getV1AdminAuditResponse401 | getV1AdminAuditResponse403 | getV1AdminAuditResponse429 | getV1AdminAuditResponse500) & {
  headers: Headers;
};

export type getV1AdminAuditResponse = (getV1AdminAuditResponseSuccess | getV1AdminAuditResponseError)

export const getGetV1AdminAuditUrl = (params?: GetV1AdminAuditParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/admin/audit?${stringifiedParams}` : `/v1/admin/audit`
}

/**
 * Returns audit_log rows newest-first, keyset-paginated. Same envelope as /v1/users.
 * @summary List audit log (admin)
 */
export const getV1AdminAudit = async (params?: GetV1AdminAuditParams, options?: RequestInit): Promise<getV1AdminAuditResponse> => {

  return orvalMutator<getV1AdminAuditResponse>(getGetV1AdminAuditUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1AdminAuditQueryKey = (params?: GetV1AdminAuditParams,) => {
    return [
    `/v1/admin/audit`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1AdminAuditQueryOptions = <TData = Awaited<ReturnType<typeof getV1AdminAudit>>, TError = InternalHandlerHttpErrorResponse>(params?: GetV1AdminAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminAudit>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1AdminAuditQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1AdminAudit>>> = ({ signal }) => getV1AdminAudit(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1AdminAudit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1AdminAuditQueryResult = NonNullable<Awaited<ReturnType<typeof getV1AdminAudit>>>
export type GetV1AdminAuditQueryError = InternalHandlerHttpErrorResponse


export function useGetV1AdminAudit<TData = Awaited<ReturnType<typeof getV1AdminAudit>>, TError = InternalHandlerHttpErrorResponse>(
 params: undefined |  GetV1AdminAuditParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminAudit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AdminAudit>>,
          TError,
          Awaited<ReturnType<typeof getV1AdminAudit>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AdminAudit<TData = Awaited<ReturnType<typeof getV1AdminAudit>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1AdminAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminAudit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AdminAudit>>,
          TError,
          Awaited<ReturnType<typeof getV1AdminAudit>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AdminAudit<TData = Awaited<ReturnType<typeof getV1AdminAudit>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1AdminAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminAudit>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List audit log (admin)
 */

export function useGetV1AdminAudit<TData = Awaited<ReturnType<typeof getV1AdminAudit>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1AdminAuditParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminAudit>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1AdminAuditQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1AdminImpersonateEndResponse200 = {
  data: InternalHandlerHttpMeResponse
  status: 200
}

export type postV1AdminImpersonateEndResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1AdminImpersonateEndResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type postV1AdminImpersonateEndResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AdminImpersonateEndResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AdminImpersonateEndResponseSuccess = (postV1AdminImpersonateEndResponse200) & {
  headers: Headers;
};
export type postV1AdminImpersonateEndResponseError = (postV1AdminImpersonateEndResponse401 | postV1AdminImpersonateEndResponse403 | postV1AdminImpersonateEndResponse429 | postV1AdminImpersonateEndResponse500) & {
  headers: Headers;
};

export type postV1AdminImpersonateEndResponse = (postV1AdminImpersonateEndResponseSuccess | postV1AdminImpersonateEndResponseError)

export const getPostV1AdminImpersonateEndUrl = () => {




  return `/v1/admin/impersonate/end`
}

/**
 * Clears `impersonating_user_id` from the admin's session via scs.Manager.Remove and writes the audit `impersonate.ended` bookend. Idempotent: with no active impersonation, returns 200 with the admin's MeResponse and writes no audit row.
 * @summary End impersonation (admin)
 */
export const postV1AdminImpersonateEnd = async ( options?: RequestInit): Promise<postV1AdminImpersonateEndResponse> => {

  return orvalMutator<postV1AdminImpersonateEndResponse>(getPostV1AdminImpersonateEndUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1AdminImpersonateEndMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AdminImpersonateEnd>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AdminImpersonateEnd>>, TError,void, TContext> => {

const mutationKey = ['postV1AdminImpersonateEnd'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AdminImpersonateEnd>>, void> = () => {


          return  postV1AdminImpersonateEnd(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AdminImpersonateEndMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AdminImpersonateEnd>>>

    export type PostV1AdminImpersonateEndMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary End impersonation (admin)
 */
export const usePostV1AdminImpersonateEnd = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AdminImpersonateEnd>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AdminImpersonateEnd>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostV1AdminImpersonateEndMutationOptions(options), queryClient);
    }
    export type getV1AdminUsersResponse200 = {
  data: InternalHandlerHttpAdminUserListResponse
  status: 200
}

export type getV1AdminUsersResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1AdminUsersResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1AdminUsersResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type getV1AdminUsersResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1AdminUsersResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1AdminUsersResponseSuccess = (getV1AdminUsersResponse200) & {
  headers: Headers;
};
export type getV1AdminUsersResponseError = (getV1AdminUsersResponse400 | getV1AdminUsersResponse401 | getV1AdminUsersResponse403 | getV1AdminUsersResponse429 | getV1AdminUsersResponse500) & {
  headers: Headers;
};

export type getV1AdminUsersResponse = (getV1AdminUsersResponseSuccess | getV1AdminUsersResponseError)

export const getGetV1AdminUsersUrl = (params?: GetV1AdminUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/admin/users?${stringifiedParams}` : `/v1/admin/users`
}

/**
 * Paginated trigram-prefix search across active (non soft-deleted) users. Soft-deleted users can be retrieved individually via GET /v1/admin/users/{id}. Same cursor envelope as the public /v1/users endpoint.
 * @summary List users (admin)
 */
export const getV1AdminUsers = async (params?: GetV1AdminUsersParams, options?: RequestInit): Promise<getV1AdminUsersResponse> => {

  return orvalMutator<getV1AdminUsersResponse>(getGetV1AdminUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1AdminUsersQueryKey = (params?: GetV1AdminUsersParams,) => {
    return [
    `/v1/admin/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1AdminUsersQueryOptions = <TData = Awaited<ReturnType<typeof getV1AdminUsers>>, TError = InternalHandlerHttpErrorResponse>(params?: GetV1AdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1AdminUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1AdminUsers>>> = ({ signal }) => getV1AdminUsers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1AdminUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getV1AdminUsers>>>
export type GetV1AdminUsersQueryError = InternalHandlerHttpErrorResponse


export function useGetV1AdminUsers<TData = Awaited<ReturnType<typeof getV1AdminUsers>>, TError = InternalHandlerHttpErrorResponse>(
 params: undefined |  GetV1AdminUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AdminUsers>>,
          TError,
          Awaited<ReturnType<typeof getV1AdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AdminUsers<TData = Awaited<ReturnType<typeof getV1AdminUsers>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1AdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AdminUsers>>,
          TError,
          Awaited<ReturnType<typeof getV1AdminUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AdminUsers<TData = Awaited<ReturnType<typeof getV1AdminUsers>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1AdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List users (admin)
 */

export function useGetV1AdminUsers<TData = Awaited<ReturnType<typeof getV1AdminUsers>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1AdminUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsers>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1AdminUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getV1AdminUsersIdResponse200 = {
  data: InternalHandlerHttpAdminUserResponse
  status: 200
}

export type getV1AdminUsersIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1AdminUsersIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1AdminUsersIdResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type getV1AdminUsersIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getV1AdminUsersIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1AdminUsersIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1AdminUsersIdResponseSuccess = (getV1AdminUsersIdResponse200) & {
  headers: Headers;
};
export type getV1AdminUsersIdResponseError = (getV1AdminUsersIdResponse400 | getV1AdminUsersIdResponse401 | getV1AdminUsersIdResponse403 | getV1AdminUsersIdResponse404 | getV1AdminUsersIdResponse429 | getV1AdminUsersIdResponse500) & {
  headers: Headers;
};

export type getV1AdminUsersIdResponse = (getV1AdminUsersIdResponseSuccess | getV1AdminUsersIdResponseError)

export const getGetV1AdminUsersIdUrl = (id: string,) => {




  return `/v1/admin/users/${id}`
}

/**
 * Returns the full row for the given user, including soft-deleted users (their `deleted_at` will be non-null). Use this when an admin needs to inspect a deleted account.
 * @summary Get user by id (admin)
 */
export const getV1AdminUsersId = async (id: string, options?: RequestInit): Promise<getV1AdminUsersIdResponse> => {

  return orvalMutator<getV1AdminUsersIdResponse>(getGetV1AdminUsersIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1AdminUsersIdQueryKey = (id: string,) => {
    return [
    `/v1/admin/users/${id}`
    ] as const;
    }


export const getGetV1AdminUsersIdQueryOptions = <TData = Awaited<ReturnType<typeof getV1AdminUsersId>>, TError = InternalHandlerHttpErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsersId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1AdminUsersIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1AdminUsersId>>> = ({ signal }) => getV1AdminUsersId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1AdminUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getV1AdminUsersId>>>
export type GetV1AdminUsersIdQueryError = InternalHandlerHttpErrorResponse


export function useGetV1AdminUsersId<TData = Awaited<ReturnType<typeof getV1AdminUsersId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AdminUsersId>>,
          TError,
          Awaited<ReturnType<typeof getV1AdminUsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AdminUsersId<TData = Awaited<ReturnType<typeof getV1AdminUsersId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AdminUsersId>>,
          TError,
          Awaited<ReturnType<typeof getV1AdminUsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AdminUsersId<TData = Awaited<ReturnType<typeof getV1AdminUsersId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsersId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user by id (admin)
 */

export function useGetV1AdminUsersId<TData = Awaited<ReturnType<typeof getV1AdminUsersId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AdminUsersId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1AdminUsersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchV1AdminUsersIdResponse200 = {
  data: InternalHandlerHttpAdminUserResponse
  status: 200
}

export type patchV1AdminUsersIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type patchV1AdminUsersIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type patchV1AdminUsersIdResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type patchV1AdminUsersIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type patchV1AdminUsersIdResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type patchV1AdminUsersIdResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type patchV1AdminUsersIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type patchV1AdminUsersIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type patchV1AdminUsersIdResponseSuccess = (patchV1AdminUsersIdResponse200) & {
  headers: Headers;
};
export type patchV1AdminUsersIdResponseError = (patchV1AdminUsersIdResponse400 | patchV1AdminUsersIdResponse401 | patchV1AdminUsersIdResponse403 | patchV1AdminUsersIdResponse404 | patchV1AdminUsersIdResponse413 | patchV1AdminUsersIdResponse422 | patchV1AdminUsersIdResponse429 | patchV1AdminUsersIdResponse500) & {
  headers: Headers;
};

export type patchV1AdminUsersIdResponse = (patchV1AdminUsersIdResponseSuccess | patchV1AdminUsersIdResponseError)

export const getPatchV1AdminUsersIdUrl = (id: string,) => {




  return `/v1/admin/users/${id}`
}

/**
 * Patches `role` (promote/demote) and/or `deleted_at` (set to now() to soft-delete). Both fields optional and may appear in the same call. Restoring a soft-deleted user (sending `deleted_at: null`) is intentionally NOT supported here yet — it returns 422.
 * @summary Update user (admin)
 */
export const patchV1AdminUsersId = async (id: string,
    internalHandlerHttpUpdateAdminUserRequest: InternalHandlerHttpUpdateAdminUserRequest, options?: RequestInit): Promise<patchV1AdminUsersIdResponse> => {

  return orvalMutator<patchV1AdminUsersIdResponse>(getPatchV1AdminUsersIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpUpdateAdminUserRequest,)
  }
);}




export const getPatchV1AdminUsersIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1AdminUsersId>>, TError,{id: string;data: InternalHandlerHttpUpdateAdminUserRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof patchV1AdminUsersId>>, TError,{id: string;data: InternalHandlerHttpUpdateAdminUserRequest}, TContext> => {

const mutationKey = ['patchV1AdminUsersId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchV1AdminUsersId>>, {id: string;data: InternalHandlerHttpUpdateAdminUserRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchV1AdminUsersId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchV1AdminUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchV1AdminUsersId>>>
    export type PatchV1AdminUsersIdMutationBody = InternalHandlerHttpUpdateAdminUserRequest
    export type PatchV1AdminUsersIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Update user (admin)
 */
export const usePatchV1AdminUsersId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1AdminUsersId>>, TError,{id: string;data: InternalHandlerHttpUpdateAdminUserRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchV1AdminUsersId>>,
        TError,
        {id: string;data: InternalHandlerHttpUpdateAdminUserRequest},
        TContext
      > => {
      return useMutation(getPatchV1AdminUsersIdMutationOptions(options), queryClient);
    }
    export type postV1AdminUsersIdImpersonateResponse200 = {
  data: InternalHandlerHttpMeResponse
  status: 200
}

export type postV1AdminUsersIdImpersonateResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1AdminUsersIdImpersonateResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1AdminUsersIdImpersonateResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type postV1AdminUsersIdImpersonateResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1AdminUsersIdImpersonateResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1AdminUsersIdImpersonateResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AdminUsersIdImpersonateResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AdminUsersIdImpersonateResponseSuccess = (postV1AdminUsersIdImpersonateResponse200) & {
  headers: Headers;
};
export type postV1AdminUsersIdImpersonateResponseError = (postV1AdminUsersIdImpersonateResponse400 | postV1AdminUsersIdImpersonateResponse401 | postV1AdminUsersIdImpersonateResponse403 | postV1AdminUsersIdImpersonateResponse404 | postV1AdminUsersIdImpersonateResponse422 | postV1AdminUsersIdImpersonateResponse429 | postV1AdminUsersIdImpersonateResponse500) & {
  headers: Headers;
};

export type postV1AdminUsersIdImpersonateResponse = (postV1AdminUsersIdImpersonateResponseSuccess | postV1AdminUsersIdImpersonateResponseError)

export const getPostV1AdminUsersIdImpersonateUrl = (id: string,) => {




  return `/v1/admin/users/${id}/impersonate`
}

/**
 * Per §8.7: validates the restriction matrix, writes the audit `impersonate.started` bookend, and stores `impersonating_user_id` on the admin's existing session via scs.Manager.Put. Subsequent requests resolve `ctx.User` to the target via the auth middleware. Returns the target's MeResponse with `impersonated_by` set.
 * @summary Start impersonating a user (admin)
 */
export const postV1AdminUsersIdImpersonate = async (id: string, options?: RequestInit): Promise<postV1AdminUsersIdImpersonateResponse> => {

  return orvalMutator<postV1AdminUsersIdImpersonateResponse>(getPostV1AdminUsersIdImpersonateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1AdminUsersIdImpersonateMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AdminUsersIdImpersonate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AdminUsersIdImpersonate>>, TError,{id: string}, TContext> => {

const mutationKey = ['postV1AdminUsersIdImpersonate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AdminUsersIdImpersonate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postV1AdminUsersIdImpersonate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AdminUsersIdImpersonateMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AdminUsersIdImpersonate>>>

    export type PostV1AdminUsersIdImpersonateMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Start impersonating a user (admin)
 */
export const usePostV1AdminUsersIdImpersonate = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AdminUsersIdImpersonate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AdminUsersIdImpersonate>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostV1AdminUsersIdImpersonateMutationOptions(options), queryClient);
    }
