/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1FriendsParams,
  InternalHandlerHttpBlockListResponse,
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpFriendListResponse,
  InternalHandlerHttpFriendRequestsResponse,
  InternalHandlerHttpFriendshipResponse,
  InternalHandlerHttpSendFriendRequestRequest
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getV1BlocksResponse200 = {
  data: InternalHandlerHttpBlockListResponse
  status: 200
}

export type getV1BlocksResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1BlocksResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1BlocksResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1BlocksResponseSuccess = (getV1BlocksResponse200) & {
  headers: Headers;
};
export type getV1BlocksResponseError = (getV1BlocksResponse401 | getV1BlocksResponse429 | getV1BlocksResponse500) & {
  headers: Headers;
};

export type getV1BlocksResponse = (getV1BlocksResponseSuccess | getV1BlocksResponseError)

export const getGetV1BlocksUrl = () => {




  return `/v1/blocks`
}

/**
 * Returns the caller's block list as public profile rows. Only the blocker sees this; the blocked party never knows. Used by the mobile settings/blocked screen (WAKEUPEXPO.md §5.1).
 * @summary List blocked users
 */
export const getV1Blocks = async ( options?: RequestInit): Promise<getV1BlocksResponse> => {

  return orvalMutator<getV1BlocksResponse>(getGetV1BlocksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1BlocksQueryKey = () => {
    return [
    `/v1/blocks`
    ] as const;
    }


export const getGetV1BlocksQueryOptions = <TData = Awaited<ReturnType<typeof getV1Blocks>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Blocks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1BlocksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Blocks>>> = ({ signal }) => getV1Blocks({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Blocks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1BlocksQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Blocks>>>
export type GetV1BlocksQueryError = InternalHandlerHttpErrorResponse


export function useGetV1Blocks<TData = Awaited<ReturnType<typeof getV1Blocks>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Blocks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Blocks>>,
          TError,
          Awaited<ReturnType<typeof getV1Blocks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Blocks<TData = Awaited<ReturnType<typeof getV1Blocks>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Blocks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Blocks>>,
          TError,
          Awaited<ReturnType<typeof getV1Blocks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Blocks<TData = Awaited<ReturnType<typeof getV1Blocks>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Blocks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List blocked users
 */

export function useGetV1Blocks<TData = Awaited<ReturnType<typeof getV1Blocks>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Blocks>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1BlocksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getV1FriendsResponse200 = {
  data: InternalHandlerHttpFriendListResponse
  status: 200
}

export type getV1FriendsResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1FriendsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1FriendsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1FriendsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1FriendsResponseSuccess = (getV1FriendsResponse200) & {
  headers: Headers;
};
export type getV1FriendsResponseError = (getV1FriendsResponse400 | getV1FriendsResponse401 | getV1FriendsResponse429 | getV1FriendsResponse500) & {
  headers: Headers;
};

export type getV1FriendsResponse = (getV1FriendsResponseSuccess | getV1FriendsResponseError)

export const getGetV1FriendsUrl = (params?: GetV1FriendsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/friends?${stringifiedParams}` : `/v1/friends`
}

/**
 * Returns the caller's accepted friendships keyset-paginated by `accepted_at DESC, id DESC` per §6.4. Each row embeds the counterparty's public profile.
 * @summary List accepted friends
 */
export const getV1Friends = async (params?: GetV1FriendsParams, options?: RequestInit): Promise<getV1FriendsResponse> => {

  return orvalMutator<getV1FriendsResponse>(getGetV1FriendsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1FriendsQueryKey = (params?: GetV1FriendsParams,) => {
    return [
    `/v1/friends`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1FriendsQueryOptions = <TData = Awaited<ReturnType<typeof getV1Friends>>, TError = InternalHandlerHttpErrorResponse>(params?: GetV1FriendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Friends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1FriendsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Friends>>> = ({ signal }) => getV1Friends(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Friends>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1FriendsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Friends>>>
export type GetV1FriendsQueryError = InternalHandlerHttpErrorResponse


export function useGetV1Friends<TData = Awaited<ReturnType<typeof getV1Friends>>, TError = InternalHandlerHttpErrorResponse>(
 params: undefined |  GetV1FriendsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Friends>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Friends>>,
          TError,
          Awaited<ReturnType<typeof getV1Friends>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Friends<TData = Awaited<ReturnType<typeof getV1Friends>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1FriendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Friends>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Friends>>,
          TError,
          Awaited<ReturnType<typeof getV1Friends>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Friends<TData = Awaited<ReturnType<typeof getV1Friends>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1FriendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Friends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List accepted friends
 */

export function useGetV1Friends<TData = Awaited<ReturnType<typeof getV1Friends>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1FriendsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Friends>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1FriendsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getV1FriendsRequestsResponse200 = {
  data: InternalHandlerHttpFriendRequestsResponse
  status: 200
}

export type getV1FriendsRequestsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1FriendsRequestsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1FriendsRequestsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1FriendsRequestsResponseSuccess = (getV1FriendsRequestsResponse200) & {
  headers: Headers;
};
export type getV1FriendsRequestsResponseError = (getV1FriendsRequestsResponse401 | getV1FriendsRequestsResponse429 | getV1FriendsRequestsResponse500) & {
  headers: Headers;
};

export type getV1FriendsRequestsResponse = (getV1FriendsRequestsResponseSuccess | getV1FriendsRequestsResponseError)

export const getGetV1FriendsRequestsUrl = () => {




  return `/v1/friends/requests`
}

/**
 * Returns the caller's pending friend requests partitioned into `incoming` (where the caller is the addressee) and `outgoing` (where the caller is the requester).
 * @summary List pending friend requests
 */
export const getV1FriendsRequests = async ( options?: RequestInit): Promise<getV1FriendsRequestsResponse> => {

  return orvalMutator<getV1FriendsRequestsResponse>(getGetV1FriendsRequestsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1FriendsRequestsQueryKey = () => {
    return [
    `/v1/friends/requests`
    ] as const;
    }


export const getGetV1FriendsRequestsQueryOptions = <TData = Awaited<ReturnType<typeof getV1FriendsRequests>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1FriendsRequests>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1FriendsRequestsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1FriendsRequests>>> = ({ signal }) => getV1FriendsRequests({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1FriendsRequests>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1FriendsRequestsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1FriendsRequests>>>
export type GetV1FriendsRequestsQueryError = InternalHandlerHttpErrorResponse


export function useGetV1FriendsRequests<TData = Awaited<ReturnType<typeof getV1FriendsRequests>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1FriendsRequests>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1FriendsRequests>>,
          TError,
          Awaited<ReturnType<typeof getV1FriendsRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1FriendsRequests<TData = Awaited<ReturnType<typeof getV1FriendsRequests>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1FriendsRequests>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1FriendsRequests>>,
          TError,
          Awaited<ReturnType<typeof getV1FriendsRequests>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1FriendsRequests<TData = Awaited<ReturnType<typeof getV1FriendsRequests>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1FriendsRequests>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List pending friend requests
 */

export function useGetV1FriendsRequests<TData = Awaited<ReturnType<typeof getV1FriendsRequests>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1FriendsRequests>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1FriendsRequestsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1FriendsRequestsResponse201 = {
  data: InternalHandlerHttpFriendshipResponse
  status: 201
}

export type postV1FriendsRequestsResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1FriendsRequestsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1FriendsRequestsResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1FriendsRequestsResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type postV1FriendsRequestsResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1FriendsRequestsResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1FriendsRequestsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1FriendsRequestsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1FriendsRequestsResponseSuccess = (postV1FriendsRequestsResponse201) & {
  headers: Headers;
};
export type postV1FriendsRequestsResponseError = (postV1FriendsRequestsResponse400 | postV1FriendsRequestsResponse401 | postV1FriendsRequestsResponse404 | postV1FriendsRequestsResponse409 | postV1FriendsRequestsResponse413 | postV1FriendsRequestsResponse422 | postV1FriendsRequestsResponse429 | postV1FriendsRequestsResponse500) & {
  headers: Headers;
};

export type postV1FriendsRequestsResponse = (postV1FriendsRequestsResponseSuccess | postV1FriendsRequestsResponseError)

export const getPostV1FriendsRequestsUrl = () => {




  return `/v1/friends/requests`
}

/**
 * Creates a `pending` friendship from the caller to the user with `username`. Returns 409 if a friendship already exists in either direction (including blocks — the response is generic so block existence isn't leaked).
 * @summary Send a friend request
 */
export const postV1FriendsRequests = async (internalHandlerHttpSendFriendRequestRequest: InternalHandlerHttpSendFriendRequestRequest, options?: RequestInit): Promise<postV1FriendsRequestsResponse> => {

  return orvalMutator<postV1FriendsRequestsResponse>(getPostV1FriendsRequestsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpSendFriendRequestRequest,)
  }
);}




export const getPostV1FriendsRequestsMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequests>>, TError,{data: InternalHandlerHttpSendFriendRequestRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequests>>, TError,{data: InternalHandlerHttpSendFriendRequestRequest}, TContext> => {

const mutationKey = ['postV1FriendsRequests'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FriendsRequests>>, {data: InternalHandlerHttpSendFriendRequestRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1FriendsRequests(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1FriendsRequestsMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FriendsRequests>>>
    export type PostV1FriendsRequestsMutationBody = InternalHandlerHttpSendFriendRequestRequest
    export type PostV1FriendsRequestsMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Send a friend request
 */
export const usePostV1FriendsRequests = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequests>>, TError,{data: InternalHandlerHttpSendFriendRequestRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FriendsRequests>>,
        TError,
        {data: InternalHandlerHttpSendFriendRequestRequest},
        TContext
      > => {
      return useMutation(getPostV1FriendsRequestsMutationOptions(options), queryClient);
    }
    export type deleteV1FriendsRequestsIdResponse204 = {
  data: void
  status: 204
}

export type deleteV1FriendsRequestsIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type deleteV1FriendsRequestsIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1FriendsRequestsIdResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type deleteV1FriendsRequestsIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1FriendsRequestsIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1FriendsRequestsIdResponseSuccess = (deleteV1FriendsRequestsIdResponse204) & {
  headers: Headers;
};
export type deleteV1FriendsRequestsIdResponseError = (deleteV1FriendsRequestsIdResponse400 | deleteV1FriendsRequestsIdResponse401 | deleteV1FriendsRequestsIdResponse409 | deleteV1FriendsRequestsIdResponse429 | deleteV1FriendsRequestsIdResponse500) & {
  headers: Headers;
};

export type deleteV1FriendsRequestsIdResponse = (deleteV1FriendsRequestsIdResponseSuccess | deleteV1FriendsRequestsIdResponseError)

export const getDeleteV1FriendsRequestsIdUrl = (id: string,) => {




  return `/v1/friends/requests/${id}`
}

/**
 * Deletes a pending friendship row that the caller sent. Only the requester may cancel; the addressee declines via the dedicated decline endpoint.
 * @summary Cancel an outgoing friend request
 */
export const deleteV1FriendsRequestsId = async (id: string, options?: RequestInit): Promise<deleteV1FriendsRequestsIdResponse> => {

  return orvalMutator<deleteV1FriendsRequestsIdResponse>(getDeleteV1FriendsRequestsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1FriendsRequestsIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsRequestsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsRequestsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteV1FriendsRequestsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1FriendsRequestsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteV1FriendsRequestsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1FriendsRequestsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1FriendsRequestsId>>>

    export type DeleteV1FriendsRequestsIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Cancel an outgoing friend request
 */
export const useDeleteV1FriendsRequestsId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsRequestsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1FriendsRequestsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteV1FriendsRequestsIdMutationOptions(options), queryClient);
    }
    export type postV1FriendsRequestsIdAcceptResponse200 = {
  data: InternalHandlerHttpFriendshipResponse
  status: 200
}

export type postV1FriendsRequestsIdAcceptResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1FriendsRequestsIdAcceptResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1FriendsRequestsIdAcceptResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type postV1FriendsRequestsIdAcceptResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1FriendsRequestsIdAcceptResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type postV1FriendsRequestsIdAcceptResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1FriendsRequestsIdAcceptResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1FriendsRequestsIdAcceptResponseSuccess = (postV1FriendsRequestsIdAcceptResponse200) & {
  headers: Headers;
};
export type postV1FriendsRequestsIdAcceptResponseError = (postV1FriendsRequestsIdAcceptResponse400 | postV1FriendsRequestsIdAcceptResponse401 | postV1FriendsRequestsIdAcceptResponse403 | postV1FriendsRequestsIdAcceptResponse404 | postV1FriendsRequestsIdAcceptResponse409 | postV1FriendsRequestsIdAcceptResponse429 | postV1FriendsRequestsIdAcceptResponse500) & {
  headers: Headers;
};

export type postV1FriendsRequestsIdAcceptResponse = (postV1FriendsRequestsIdAcceptResponseSuccess | postV1FriendsRequestsIdAcceptResponseError)

export const getPostV1FriendsRequestsIdAcceptUrl = (id: string,) => {




  return `/v1/friends/requests/${id}/accept`
}

/**
 * Transitions a pending friendship to accepted. Only the addressee of the request may accept; the requester gets 403. Returns the rendered friendship envelope per §6.2.
 * @summary Accept a friend request
 */
export const postV1FriendsRequestsIdAccept = async (id: string, options?: RequestInit): Promise<postV1FriendsRequestsIdAcceptResponse> => {

  return orvalMutator<postV1FriendsRequestsIdAcceptResponse>(getPostV1FriendsRequestsIdAcceptUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1FriendsRequestsIdAcceptMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequestsIdAccept>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequestsIdAccept>>, TError,{id: string}, TContext> => {

const mutationKey = ['postV1FriendsRequestsIdAccept'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FriendsRequestsIdAccept>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postV1FriendsRequestsIdAccept(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1FriendsRequestsIdAcceptMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FriendsRequestsIdAccept>>>

    export type PostV1FriendsRequestsIdAcceptMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Accept a friend request
 */
export const usePostV1FriendsRequestsIdAccept = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequestsIdAccept>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FriendsRequestsIdAccept>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostV1FriendsRequestsIdAcceptMutationOptions(options), queryClient);
    }
    export type postV1FriendsRequestsIdDeclineResponse204 = {
  data: void
  status: 204
}

export type postV1FriendsRequestsIdDeclineResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1FriendsRequestsIdDeclineResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1FriendsRequestsIdDeclineResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type postV1FriendsRequestsIdDeclineResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1FriendsRequestsIdDeclineResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type postV1FriendsRequestsIdDeclineResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1FriendsRequestsIdDeclineResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1FriendsRequestsIdDeclineResponseSuccess = (postV1FriendsRequestsIdDeclineResponse204) & {
  headers: Headers;
};
export type postV1FriendsRequestsIdDeclineResponseError = (postV1FriendsRequestsIdDeclineResponse400 | postV1FriendsRequestsIdDeclineResponse401 | postV1FriendsRequestsIdDeclineResponse403 | postV1FriendsRequestsIdDeclineResponse404 | postV1FriendsRequestsIdDeclineResponse409 | postV1FriendsRequestsIdDeclineResponse429 | postV1FriendsRequestsIdDeclineResponse500) & {
  headers: Headers;
};

export type postV1FriendsRequestsIdDeclineResponse = (postV1FriendsRequestsIdDeclineResponseSuccess | postV1FriendsRequestsIdDeclineResponseError)

export const getPostV1FriendsRequestsIdDeclineUrl = (id: string,) => {




  return `/v1/friends/requests/${id}/decline`
}

/**
 * Deletes a pending friendship row. Only the addressee may decline; the requester gets 403. Idempotent in spirit — calling on an already-decided request surfaces 409 because the row no longer exists.
 * @summary Decline a friend request
 */
export const postV1FriendsRequestsIdDecline = async (id: string, options?: RequestInit): Promise<postV1FriendsRequestsIdDeclineResponse> => {

  return orvalMutator<postV1FriendsRequestsIdDeclineResponse>(getPostV1FriendsRequestsIdDeclineUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1FriendsRequestsIdDeclineMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequestsIdDecline>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequestsIdDecline>>, TError,{id: string}, TContext> => {

const mutationKey = ['postV1FriendsRequestsIdDecline'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FriendsRequestsIdDecline>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postV1FriendsRequestsIdDecline(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1FriendsRequestsIdDeclineMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FriendsRequestsIdDecline>>>

    export type PostV1FriendsRequestsIdDeclineMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Decline a friend request
 */
export const usePostV1FriendsRequestsIdDecline = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsRequestsIdDecline>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FriendsRequestsIdDecline>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostV1FriendsRequestsIdDeclineMutationOptions(options), queryClient);
    }
    export type deleteV1FriendsUserIdResponse204 = {
  data: void
  status: 204
}

export type deleteV1FriendsUserIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type deleteV1FriendsUserIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1FriendsUserIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type deleteV1FriendsUserIdResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type deleteV1FriendsUserIdResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type deleteV1FriendsUserIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1FriendsUserIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1FriendsUserIdResponseSuccess = (deleteV1FriendsUserIdResponse204) & {
  headers: Headers;
};
export type deleteV1FriendsUserIdResponseError = (deleteV1FriendsUserIdResponse400 | deleteV1FriendsUserIdResponse401 | deleteV1FriendsUserIdResponse404 | deleteV1FriendsUserIdResponse409 | deleteV1FriendsUserIdResponse422 | deleteV1FriendsUserIdResponse429 | deleteV1FriendsUserIdResponse500) & {
  headers: Headers;
};

export type deleteV1FriendsUserIdResponse = (deleteV1FriendsUserIdResponseSuccess | deleteV1FriendsUserIdResponseError)

export const getDeleteV1FriendsUserIdUrl = (userId: string,) => {




  return `/v1/friends/${userId}`
}

/**
 * Removes an accepted friendship between the caller and `user_id`. Either side can unfriend; pending or blocked relationships surface as 409. Self-unfriend is a 422 since no such row exists.
 * @summary Unfriend a user
 */
export const deleteV1FriendsUserId = async (userId: string, options?: RequestInit): Promise<deleteV1FriendsUserIdResponse> => {

  return orvalMutator<deleteV1FriendsUserIdResponse>(getDeleteV1FriendsUserIdUrl(userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1FriendsUserIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsUserId>>, TError,{userId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsUserId>>, TError,{userId: string}, TContext> => {

const mutationKey = ['deleteV1FriendsUserId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1FriendsUserId>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  deleteV1FriendsUserId(userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1FriendsUserIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1FriendsUserId>>>

    export type DeleteV1FriendsUserIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Unfriend a user
 */
export const useDeleteV1FriendsUserId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsUserId>>, TError,{userId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1FriendsUserId>>,
        TError,
        {userId: string},
        TContext
      > => {
      return useMutation(getDeleteV1FriendsUserIdMutationOptions(options), queryClient);
    }
    export type postV1FriendsUserIdBlockResponse201 = {
  data: InternalHandlerHttpFriendshipResponse
  status: 201
}

export type postV1FriendsUserIdBlockResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1FriendsUserIdBlockResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1FriendsUserIdBlockResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type postV1FriendsUserIdBlockResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1FriendsUserIdBlockResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type postV1FriendsUserIdBlockResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1FriendsUserIdBlockResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1FriendsUserIdBlockResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1FriendsUserIdBlockResponseSuccess = (postV1FriendsUserIdBlockResponse201) & {
  headers: Headers;
};
export type postV1FriendsUserIdBlockResponseError = (postV1FriendsUserIdBlockResponse400 | postV1FriendsUserIdBlockResponse401 | postV1FriendsUserIdBlockResponse403 | postV1FriendsUserIdBlockResponse404 | postV1FriendsUserIdBlockResponse409 | postV1FriendsUserIdBlockResponse422 | postV1FriendsUserIdBlockResponse429 | postV1FriendsUserIdBlockResponse500) & {
  headers: Headers;
};

export type postV1FriendsUserIdBlockResponse = (postV1FriendsUserIdBlockResponseSuccess | postV1FriendsUserIdBlockResponseError)

export const getPostV1FriendsUserIdBlockUrl = (userId: string,) => {




  return `/v1/friends/${userId}/block`
}

/**
 * Records the caller as having blocked the target. Replaces any pending/accepted friendship between the two. Refuses (403) if the target has already blocked the caller — the existing block stays in place and the response is intentionally generic.
 * @summary Block a user
 */
export const postV1FriendsUserIdBlock = async (userId: string, options?: RequestInit): Promise<postV1FriendsUserIdBlockResponse> => {

  return orvalMutator<postV1FriendsUserIdBlockResponse>(getPostV1FriendsUserIdBlockUrl(userId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1FriendsUserIdBlockMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsUserIdBlock>>, TError,{userId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsUserIdBlock>>, TError,{userId: string}, TContext> => {

const mutationKey = ['postV1FriendsUserIdBlock'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1FriendsUserIdBlock>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  postV1FriendsUserIdBlock(userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1FriendsUserIdBlockMutationResult = NonNullable<Awaited<ReturnType<typeof postV1FriendsUserIdBlock>>>

    export type PostV1FriendsUserIdBlockMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Block a user
 */
export const usePostV1FriendsUserIdBlock = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1FriendsUserIdBlock>>, TError,{userId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1FriendsUserIdBlock>>,
        TError,
        {userId: string},
        TContext
      > => {
      return useMutation(getPostV1FriendsUserIdBlockMutationOptions(options), queryClient);
    }
    export type deleteV1FriendsUserIdBlockResponse204 = {
  data: void
  status: 204
}

export type deleteV1FriendsUserIdBlockResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type deleteV1FriendsUserIdBlockResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1FriendsUserIdBlockResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type deleteV1FriendsUserIdBlockResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type deleteV1FriendsUserIdBlockResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1FriendsUserIdBlockResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1FriendsUserIdBlockResponseSuccess = (deleteV1FriendsUserIdBlockResponse204) & {
  headers: Headers;
};
export type deleteV1FriendsUserIdBlockResponseError = (deleteV1FriendsUserIdBlockResponse400 | deleteV1FriendsUserIdBlockResponse401 | deleteV1FriendsUserIdBlockResponse404 | deleteV1FriendsUserIdBlockResponse422 | deleteV1FriendsUserIdBlockResponse429 | deleteV1FriendsUserIdBlockResponse500) & {
  headers: Headers;
};

export type deleteV1FriendsUserIdBlockResponse = (deleteV1FriendsUserIdBlockResponseSuccess | deleteV1FriendsUserIdBlockResponseError)

export const getDeleteV1FriendsUserIdBlockUrl = (userId: string,) => {




  return `/v1/friends/${userId}/block`
}

/**
 * Removes the caller's block on the target user. The target party can't call this — only the original blocker can. Reachable via both `DELETE /v1/friends/{user_id}/block` and `DELETE /v1/blocks/{user_id}`.
 * @summary Unblock a user
 */
export const deleteV1FriendsUserIdBlock = async (userId: string, options?: RequestInit): Promise<deleteV1FriendsUserIdBlockResponse> => {

  return orvalMutator<deleteV1FriendsUserIdBlockResponse>(getDeleteV1FriendsUserIdBlockUrl(userId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1FriendsUserIdBlockMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsUserIdBlock>>, TError,{userId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsUserIdBlock>>, TError,{userId: string}, TContext> => {

const mutationKey = ['deleteV1FriendsUserIdBlock'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1FriendsUserIdBlock>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  deleteV1FriendsUserIdBlock(userId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1FriendsUserIdBlockMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1FriendsUserIdBlock>>>

    export type DeleteV1FriendsUserIdBlockMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Unblock a user
 */
export const useDeleteV1FriendsUserIdBlock = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1FriendsUserIdBlock>>, TError,{userId: string}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1FriendsUserIdBlock>>,
        TError,
        {userId: string},
        TContext
      > => {
      return useMutation(getDeleteV1FriendsUserIdBlockMutationOptions(options), queryClient);
    }
