/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1UsersParams,
  InternalHandlerHttpAvatarUploadResponse,
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpMeResponse,
  InternalHandlerHttpNotificationPreferencesResponse,
  InternalHandlerHttpUpdateMeRequest,
  InternalHandlerHttpUpdateNotificationPreferencesRequest,
  InternalHandlerHttpUserListResponse,
  InternalHandlerHttpUserResponse,
  PostV1UsersMeAvatarBody
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getV1UsersResponse200 = {
  data: InternalHandlerHttpUserListResponse
  status: 200
}

export type getV1UsersResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1UsersResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1UsersResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1UsersResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1UsersResponseSuccess = (getV1UsersResponse200) & {
  headers: Headers;
};
export type getV1UsersResponseError = (getV1UsersResponse400 | getV1UsersResponse401 | getV1UsersResponse429 | getV1UsersResponse500) & {
  headers: Headers;
};

export type getV1UsersResponse = (getV1UsersResponseSuccess | getV1UsersResponseError)

export const getGetV1UsersUrl = (params?: GetV1UsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/users?${stringifiedParams}` : `/v1/users`
}

/**
 * Returns up to `limit` users whose username or display_name matches `q` (case-insensitive trigram). Empty `q` returns the catalog ordered by `created_at DESC, id DESC`. Pagination is keyset (§6.4) — never offset.
 * @summary Search users
 */
export const getV1Users = async (params?: GetV1UsersParams, options?: RequestInit): Promise<getV1UsersResponse> => {

  return orvalMutator<getV1UsersResponse>(getGetV1UsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1UsersQueryKey = (params?: GetV1UsersParams,) => {
    return [
    `/v1/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1UsersQueryOptions = <TData = Awaited<ReturnType<typeof getV1Users>>, TError = InternalHandlerHttpErrorResponse>(params?: GetV1UsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Users>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1UsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Users>>> = ({ signal }) => getV1Users(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Users>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1UsersQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Users>>>
export type GetV1UsersQueryError = InternalHandlerHttpErrorResponse


export function useGetV1Users<TData = Awaited<ReturnType<typeof getV1Users>>, TError = InternalHandlerHttpErrorResponse>(
 params: undefined |  GetV1UsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Users>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Users>>,
          TError,
          Awaited<ReturnType<typeof getV1Users>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Users<TData = Awaited<ReturnType<typeof getV1Users>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1UsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Users>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Users>>,
          TError,
          Awaited<ReturnType<typeof getV1Users>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Users<TData = Awaited<ReturnType<typeof getV1Users>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1UsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Users>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search users
 */

export function useGetV1Users<TData = Awaited<ReturnType<typeof getV1Users>>, TError = InternalHandlerHttpErrorResponse>(
 params?: GetV1UsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Users>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1UsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteV1UsersMeResponse204 = {
  data: void
  status: 204
}

export type deleteV1UsersMeResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1UsersMeResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type deleteV1UsersMeResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1UsersMeResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1UsersMeResponseSuccess = (deleteV1UsersMeResponse204) & {
  headers: Headers;
};
export type deleteV1UsersMeResponseError = (deleteV1UsersMeResponse401 | deleteV1UsersMeResponse403 | deleteV1UsersMeResponse429 | deleteV1UsersMeResponse500) & {
  headers: Headers;
};

export type deleteV1UsersMeResponse = (deleteV1UsersMeResponseSuccess | deleteV1UsersMeResponseError)

export const getDeleteV1UsersMeUrl = () => {




  return `/v1/users/me`
}

/**
 * Soft-deletes the authenticated user. Their content (messages, etc.) is preserved per §4.6 but they become invisible to lists/search and cannot log in.
 * @summary Soft-delete current user
 */
export const deleteV1UsersMe = async ( options?: RequestInit): Promise<deleteV1UsersMeResponse> => {

  return orvalMutator<deleteV1UsersMeResponse>(getDeleteV1UsersMeUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1UsersMeMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1UsersMe>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1UsersMe>>, TError,void, TContext> => {

const mutationKey = ['deleteV1UsersMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1UsersMe>>, void> = () => {


          return  deleteV1UsersMe(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1UsersMeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1UsersMe>>>

    export type DeleteV1UsersMeMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Soft-delete current user
 */
export const useDeleteV1UsersMe = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1UsersMe>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1UsersMe>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteV1UsersMeMutationOptions(options), queryClient);
    }
    export type patchV1UsersMeResponse200 = {
  data: InternalHandlerHttpMeResponse
  status: 200
}

export type patchV1UsersMeResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type patchV1UsersMeResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type patchV1UsersMeResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type patchV1UsersMeResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type patchV1UsersMeResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type patchV1UsersMeResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type patchV1UsersMeResponseSuccess = (patchV1UsersMeResponse200) & {
  headers: Headers;
};
export type patchV1UsersMeResponseError = (patchV1UsersMeResponse400 | patchV1UsersMeResponse401 | patchV1UsersMeResponse413 | patchV1UsersMeResponse422 | patchV1UsersMeResponse429 | patchV1UsersMeResponse500) & {
  headers: Headers;
};

export type patchV1UsersMeResponse = (patchV1UsersMeResponseSuccess | patchV1UsersMeResponseError)

export const getPatchV1UsersMeUrl = () => {




  return `/v1/users/me`
}

/**
 * Patches `display_name`, `avatar_url`, `color_scheme`, `bio`, or `status_emoji`. Each field is optional; omitted (or null) values are left unchanged. Send `""` for `bio`/`status_emoji` to clear them.
 * @summary Update current user's profile
 */
export const patchV1UsersMe = async (internalHandlerHttpUpdateMeRequest: InternalHandlerHttpUpdateMeRequest, options?: RequestInit): Promise<patchV1UsersMeResponse> => {

  return orvalMutator<patchV1UsersMeResponse>(getPatchV1UsersMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpUpdateMeRequest,)
  }
);}




export const getPatchV1UsersMeMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1UsersMe>>, TError,{data: InternalHandlerHttpUpdateMeRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof patchV1UsersMe>>, TError,{data: InternalHandlerHttpUpdateMeRequest}, TContext> => {

const mutationKey = ['patchV1UsersMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchV1UsersMe>>, {data: InternalHandlerHttpUpdateMeRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchV1UsersMe(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchV1UsersMeMutationResult = NonNullable<Awaited<ReturnType<typeof patchV1UsersMe>>>
    export type PatchV1UsersMeMutationBody = InternalHandlerHttpUpdateMeRequest
    export type PatchV1UsersMeMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Update current user's profile
 */
export const usePatchV1UsersMe = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1UsersMe>>, TError,{data: InternalHandlerHttpUpdateMeRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchV1UsersMe>>,
        TError,
        {data: InternalHandlerHttpUpdateMeRequest},
        TContext
      > => {
      return useMutation(getPatchV1UsersMeMutationOptions(options), queryClient);
    }
    export type postV1UsersMeAvatarResponse200 = {
  data: InternalHandlerHttpAvatarUploadResponse
  status: 200
}

export type postV1UsersMeAvatarResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1UsersMeAvatarResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1UsersMeAvatarResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1UsersMeAvatarResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1UsersMeAvatarResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1UsersMeAvatarResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1UsersMeAvatarResponseSuccess = (postV1UsersMeAvatarResponse200) & {
  headers: Headers;
};
export type postV1UsersMeAvatarResponseError = (postV1UsersMeAvatarResponse400 | postV1UsersMeAvatarResponse401 | postV1UsersMeAvatarResponse413 | postV1UsersMeAvatarResponse422 | postV1UsersMeAvatarResponse429 | postV1UsersMeAvatarResponse500) & {
  headers: Headers;
};

export type postV1UsersMeAvatarResponse = (postV1UsersMeAvatarResponseSuccess | postV1UsersMeAvatarResponseError)

export const getPostV1UsersMeAvatarUrl = () => {




  return `/v1/users/me/avatar`
}

/**
 * Accepts a multipart form with a single `file` field. Max 5 MiB; server-side MIME detection (§9.2) accepts image/png, image/jpeg, image/gif, image/webp.
 * @summary Upload current user's avatar
 */
export const postV1UsersMeAvatar = async (postV1UsersMeAvatarBody: PostV1UsersMeAvatarBody, options?: RequestInit): Promise<postV1UsersMeAvatarResponse> => {
    const formData = new FormData();
formData.append(`file`, postV1UsersMeAvatarBody.file);

  return orvalMutator<postV1UsersMeAvatarResponse>(getPostV1UsersMeAvatarUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getPostV1UsersMeAvatarMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeAvatar>>, TError,{data: PostV1UsersMeAvatarBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeAvatar>>, TError,{data: PostV1UsersMeAvatarBody}, TContext> => {

const mutationKey = ['postV1UsersMeAvatar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1UsersMeAvatar>>, {data: PostV1UsersMeAvatarBody}> = (props) => {
          const {data} = props ?? {};

          return  postV1UsersMeAvatar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1UsersMeAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof postV1UsersMeAvatar>>>
    export type PostV1UsersMeAvatarMutationBody = PostV1UsersMeAvatarBody
    export type PostV1UsersMeAvatarMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Upload current user's avatar
 */
export const usePostV1UsersMeAvatar = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeAvatar>>, TError,{data: PostV1UsersMeAvatarBody}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1UsersMeAvatar>>,
        TError,
        {data: PostV1UsersMeAvatarBody},
        TContext
      > => {
      return useMutation(getPostV1UsersMeAvatarMutationOptions(options), queryClient);
    }
    export type deleteV1UsersMeAvatarResponse200 = {
  data: InternalHandlerHttpAvatarUploadResponse
  status: 200
}

export type deleteV1UsersMeAvatarResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1UsersMeAvatarResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type deleteV1UsersMeAvatarResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1UsersMeAvatarResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1UsersMeAvatarResponseSuccess = (deleteV1UsersMeAvatarResponse200) & {
  headers: Headers;
};
export type deleteV1UsersMeAvatarResponseError = (deleteV1UsersMeAvatarResponse401 | deleteV1UsersMeAvatarResponse404 | deleteV1UsersMeAvatarResponse429 | deleteV1UsersMeAvatarResponse500) & {
  headers: Headers;
};

export type deleteV1UsersMeAvatarResponse = (deleteV1UsersMeAvatarResponseSuccess | deleteV1UsersMeAvatarResponseError)

export const getDeleteV1UsersMeAvatarUrl = () => {




  return `/v1/users/me/avatar`
}

/**
 * Sets `avatar_url = NULL` on the authenticated user and best-effort deletes the underlying S3 object. Idempotent — calling twice on a user without an avatar returns 200 with no avatar_url.
 * @summary Remove current user's avatar
 */
export const deleteV1UsersMeAvatar = async ( options?: RequestInit): Promise<deleteV1UsersMeAvatarResponse> => {

  return orvalMutator<deleteV1UsersMeAvatarResponse>(getDeleteV1UsersMeAvatarUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1UsersMeAvatarMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1UsersMeAvatar>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1UsersMeAvatar>>, TError,void, TContext> => {

const mutationKey = ['deleteV1UsersMeAvatar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1UsersMeAvatar>>, void> = () => {


          return  deleteV1UsersMeAvatar(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1UsersMeAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1UsersMeAvatar>>>

    export type DeleteV1UsersMeAvatarMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Remove current user's avatar
 */
export const useDeleteV1UsersMeAvatar = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1UsersMeAvatar>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1UsersMeAvatar>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteV1UsersMeAvatarMutationOptions(options), queryClient);
    }
    export type getV1UsersMeNotificationsResponse200 = {
  data: InternalHandlerHttpNotificationPreferencesResponse
  status: 200
}

export type getV1UsersMeNotificationsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1UsersMeNotificationsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1UsersMeNotificationsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1UsersMeNotificationsResponseSuccess = (getV1UsersMeNotificationsResponse200) & {
  headers: Headers;
};
export type getV1UsersMeNotificationsResponseError = (getV1UsersMeNotificationsResponse401 | getV1UsersMeNotificationsResponse429 | getV1UsersMeNotificationsResponse500) & {
  headers: Headers;
};

export type getV1UsersMeNotificationsResponse = (getV1UsersMeNotificationsResponseSuccess | getV1UsersMeNotificationsResponseError)

export const getGetV1UsersMeNotificationsUrl = () => {




  return `/v1/users/me/notifications`
}

/**
 * Returns the per-category push-notification toggles. The row is auto-created with defaults (all true) on first read.
 * @summary Get current user's notification preferences
 */
export const getV1UsersMeNotifications = async ( options?: RequestInit): Promise<getV1UsersMeNotificationsResponse> => {

  return orvalMutator<getV1UsersMeNotificationsResponse>(getGetV1UsersMeNotificationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1UsersMeNotificationsQueryKey = () => {
    return [
    `/v1/users/me/notifications`
    ] as const;
    }


export const getGetV1UsersMeNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1UsersMeNotificationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1UsersMeNotifications>>> = ({ signal }) => getV1UsersMeNotifications({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1UsersMeNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1UsersMeNotifications>>>
export type GetV1UsersMeNotificationsQueryError = InternalHandlerHttpErrorResponse


export function useGetV1UsersMeNotifications<TData = Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1UsersMeNotifications>>,
          TError,
          Awaited<ReturnType<typeof getV1UsersMeNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1UsersMeNotifications<TData = Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1UsersMeNotifications>>,
          TError,
          Awaited<ReturnType<typeof getV1UsersMeNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1UsersMeNotifications<TData = Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current user's notification preferences
 */

export function useGetV1UsersMeNotifications<TData = Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersMeNotifications>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1UsersMeNotificationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type patchV1UsersMeNotificationsResponse200 = {
  data: InternalHandlerHttpNotificationPreferencesResponse
  status: 200
}

export type patchV1UsersMeNotificationsResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type patchV1UsersMeNotificationsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type patchV1UsersMeNotificationsResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type patchV1UsersMeNotificationsResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type patchV1UsersMeNotificationsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type patchV1UsersMeNotificationsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type patchV1UsersMeNotificationsResponseSuccess = (patchV1UsersMeNotificationsResponse200) & {
  headers: Headers;
};
export type patchV1UsersMeNotificationsResponseError = (patchV1UsersMeNotificationsResponse400 | patchV1UsersMeNotificationsResponse401 | patchV1UsersMeNotificationsResponse413 | patchV1UsersMeNotificationsResponse422 | patchV1UsersMeNotificationsResponse429 | patchV1UsersMeNotificationsResponse500) & {
  headers: Headers;
};

export type patchV1UsersMeNotificationsResponse = (patchV1UsersMeNotificationsResponseSuccess | patchV1UsersMeNotificationsResponseError)

export const getPatchV1UsersMeNotificationsUrl = () => {




  return `/v1/users/me/notifications`
}

/**
 * Patches any subset of `direct_messages`, `group_messages`, `friend_requests`, `calls`, `theme_scheme`, `theme_mode_preference`. Omitted fields are unchanged. Theme enum values are validated; invalid values return 400 with a `theme_scheme` / `theme_mode_preference` field error.
 * @summary Update current user's notification + theme preferences
 */
export const patchV1UsersMeNotifications = async (internalHandlerHttpUpdateNotificationPreferencesRequest: InternalHandlerHttpUpdateNotificationPreferencesRequest, options?: RequestInit): Promise<patchV1UsersMeNotificationsResponse> => {

  return orvalMutator<patchV1UsersMeNotificationsResponse>(getPatchV1UsersMeNotificationsUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpUpdateNotificationPreferencesRequest,)
  }
);}




export const getPatchV1UsersMeNotificationsMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1UsersMeNotifications>>, TError,{data: InternalHandlerHttpUpdateNotificationPreferencesRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof patchV1UsersMeNotifications>>, TError,{data: InternalHandlerHttpUpdateNotificationPreferencesRequest}, TContext> => {

const mutationKey = ['patchV1UsersMeNotifications'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchV1UsersMeNotifications>>, {data: InternalHandlerHttpUpdateNotificationPreferencesRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchV1UsersMeNotifications(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchV1UsersMeNotificationsMutationResult = NonNullable<Awaited<ReturnType<typeof patchV1UsersMeNotifications>>>
    export type PatchV1UsersMeNotificationsMutationBody = InternalHandlerHttpUpdateNotificationPreferencesRequest
    export type PatchV1UsersMeNotificationsMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Update current user's notification + theme preferences
 */
export const usePatchV1UsersMeNotifications = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1UsersMeNotifications>>, TError,{data: InternalHandlerHttpUpdateNotificationPreferencesRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchV1UsersMeNotifications>>,
        TError,
        {data: InternalHandlerHttpUpdateNotificationPreferencesRequest},
        TContext
      > => {
      return useMutation(getPatchV1UsersMeNotificationsMutationOptions(options), queryClient);
    }
    export type postV1UsersMeOnboardResponse200 = {
  data: InternalHandlerHttpMeResponse
  status: 200
}

export type postV1UsersMeOnboardResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1UsersMeOnboardResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1UsersMeOnboardResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1UsersMeOnboardResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1UsersMeOnboardResponseSuccess = (postV1UsersMeOnboardResponse200) & {
  headers: Headers;
};
export type postV1UsersMeOnboardResponseError = (postV1UsersMeOnboardResponse401 | postV1UsersMeOnboardResponse404 | postV1UsersMeOnboardResponse429 | postV1UsersMeOnboardResponse500) & {
  headers: Headers;
};

export type postV1UsersMeOnboardResponse = (postV1UsersMeOnboardResponseSuccess | postV1UsersMeOnboardResponseError)

export const getPostV1UsersMeOnboardUrl = () => {




  return `/v1/users/me/onboard`
}

/**
 * Sets `onboarded_at = now()` on the authenticated user (idempotent — second call preserves the original timestamp). Returns the updated /v1/auth/me view so the client can update its cache.
 * @summary Mark onboarding complete
 */
export const postV1UsersMeOnboard = async ( options?: RequestInit): Promise<postV1UsersMeOnboardResponse> => {

  return orvalMutator<postV1UsersMeOnboardResponse>(getPostV1UsersMeOnboardUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1UsersMeOnboardMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeOnboard>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeOnboard>>, TError,void, TContext> => {

const mutationKey = ['postV1UsersMeOnboard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1UsersMeOnboard>>, void> = () => {


          return  postV1UsersMeOnboard(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1UsersMeOnboardMutationResult = NonNullable<Awaited<ReturnType<typeof postV1UsersMeOnboard>>>

    export type PostV1UsersMeOnboardMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Mark onboarding complete
 */
export const usePostV1UsersMeOnboard = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1UsersMeOnboard>>, TError,void, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1UsersMeOnboard>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostV1UsersMeOnboardMutationOptions(options), queryClient);
    }
    export type getV1UsersIdResponse200 = {
  data: InternalHandlerHttpUserResponse
  status: 200
}

export type getV1UsersIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1UsersIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1UsersIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getV1UsersIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1UsersIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1UsersIdResponseSuccess = (getV1UsersIdResponse200) & {
  headers: Headers;
};
export type getV1UsersIdResponseError = (getV1UsersIdResponse400 | getV1UsersIdResponse401 | getV1UsersIdResponse404 | getV1UsersIdResponse429 | getV1UsersIdResponse500) & {
  headers: Headers;
};

export type getV1UsersIdResponse = (getV1UsersIdResponseSuccess | getV1UsersIdResponseError)

export const getGetV1UsersIdUrl = (id: string,) => {




  return `/v1/users/${id}`
}

/**
 * Returns the public profile (username, display_name, avatar). Soft-deleted users collapse to the placeholder shape (§4.6).
 * @summary Get user by id
 */
export const getV1UsersId = async (id: string, options?: RequestInit): Promise<getV1UsersIdResponse> => {

  return orvalMutator<getV1UsersIdResponse>(getGetV1UsersIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1UsersIdQueryKey = (id: string,) => {
    return [
    `/v1/users/${id}`
    ] as const;
    }


export const getGetV1UsersIdQueryOptions = <TData = Awaited<ReturnType<typeof getV1UsersId>>, TError = InternalHandlerHttpErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1UsersIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1UsersId>>> = ({ signal }) => getV1UsersId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1UsersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1UsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getV1UsersId>>>
export type GetV1UsersIdQueryError = InternalHandlerHttpErrorResponse


export function useGetV1UsersId<TData = Awaited<ReturnType<typeof getV1UsersId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1UsersId>>,
          TError,
          Awaited<ReturnType<typeof getV1UsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1UsersId<TData = Awaited<ReturnType<typeof getV1UsersId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1UsersId>>,
          TError,
          Awaited<ReturnType<typeof getV1UsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1UsersId<TData = Awaited<ReturnType<typeof getV1UsersId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user by id
 */

export function useGetV1UsersId<TData = Awaited<ReturnType<typeof getV1UsersId>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1UsersId>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1UsersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






