/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  InternalHandlerHttpContactsMatchRequest,
  InternalHandlerHttpContactsMatchResponse,
  InternalHandlerHttpErrorResponse
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postV1ContactsMatchResponse200 = {
  data: InternalHandlerHttpContactsMatchResponse
  status: 200
}

export type postV1ContactsMatchResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1ContactsMatchResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1ContactsMatchResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1ContactsMatchResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1ContactsMatchResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1ContactsMatchResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1ContactsMatchResponseSuccess = (postV1ContactsMatchResponse200) & {
  headers: Headers;
};
export type postV1ContactsMatchResponseError = (postV1ContactsMatchResponse400 | postV1ContactsMatchResponse401 | postV1ContactsMatchResponse413 | postV1ContactsMatchResponse422 | postV1ContactsMatchResponse429 | postV1ContactsMatchResponse500) & {
  headers: Headers;
};

export type postV1ContactsMatchResponse = (postV1ContactsMatchResponseSuccess | postV1ContactsMatchResponseError)

export const getPostV1ContactsMatchUrl = () => {




  return `/v1/contacts/match`
}

/**
 * Privacy-preserving contacts sync. Client SHA-256s each contact email (`sha256(lower(trim(email)))`), hex-encodes, and POSTs the slice. Server hex-decodes and matches against `users.email_hash` (bytea, indexed). Unmatched hashes are not echoed and not logged. Soft-deleted users are excluded. Cap 1000 entries per request — chunk client-side past that.
 * @summary Match contacts by email hash
 */
export const postV1ContactsMatch = async (internalHandlerHttpContactsMatchRequest: InternalHandlerHttpContactsMatchRequest, options?: RequestInit): Promise<postV1ContactsMatchResponse> => {

  return orvalMutator<postV1ContactsMatchResponse>(getPostV1ContactsMatchUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpContactsMatchRequest,)
  }
);}




export const getPostV1ContactsMatchMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ContactsMatch>>, TError,{data: InternalHandlerHttpContactsMatchRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postV1ContactsMatch>>, TError,{data: InternalHandlerHttpContactsMatchRequest}, TContext> => {

const mutationKey = ['postV1ContactsMatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1ContactsMatch>>, {data: InternalHandlerHttpContactsMatchRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1ContactsMatch(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ContactsMatchMutationResult = NonNullable<Awaited<ReturnType<typeof postV1ContactsMatch>>>
    export type PostV1ContactsMatchMutationBody = InternalHandlerHttpContactsMatchRequest
    export type PostV1ContactsMatchMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Match contacts by email hash
 */
export const usePostV1ContactsMatch = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ContactsMatch>>, TError,{data: InternalHandlerHttpContactsMatchRequest}, TContext>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1ContactsMatch>>,
        TError,
        {data: InternalHandlerHttpContactsMatchRequest},
        TContext
      > => {
      return useMutation(getPostV1ContactsMatchMutationOptions(options), queryClient);
    }
