/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1OpenapiJson200,
  GetWellKnownAppleAppSiteAssociation200,
  GetWellKnownAssetlinksJson200Item,
  GithubComCadenlundWakeupAppsBackendInternalHandlerHttpErrorResponse,
  GithubComCadenlundWakeupAppsBackendInternalHandlerHttpHealthzResponse,
  InternalHandlerHttpErrorResponse
} from '../../model';

import { orvalMutator } from '../../orval-mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getWellKnownAppleAppSiteAssociationResponse200 = {
  data: GetWellKnownAppleAppSiteAssociation200
  status: 200
}

export type getWellKnownAppleAppSiteAssociationResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getWellKnownAppleAppSiteAssociationResponseSuccess = (getWellKnownAppleAppSiteAssociationResponse200) & {
  headers: Headers;
};
export type getWellKnownAppleAppSiteAssociationResponseError = (getWellKnownAppleAppSiteAssociationResponse404) & {
  headers: Headers;
};

export type getWellKnownAppleAppSiteAssociationResponse = (getWellKnownAppleAppSiteAssociationResponseSuccess | getWellKnownAppleAppSiteAssociationResponseError)

export const getGetWellKnownAppleAppSiteAssociationUrl = () => {




  return `/.well-known/apple-app-site-association`
}

/**
 * Static JSON consumed by iOS to enable Universal Links to `app.wakeup.client`. Returns 404 when `IOS_APP_ID` isn't configured. Apple's CDN caches this; clients should not rely on dynamic content.
 * @summary Apple App Site Association
 */
export const getWellKnownAppleAppSiteAssociation = async ( options?: RequestInit): Promise<getWellKnownAppleAppSiteAssociationResponse> => {

  return orvalMutator<getWellKnownAppleAppSiteAssociationResponse>(getGetWellKnownAppleAppSiteAssociationUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWellKnownAppleAppSiteAssociationQueryKey = () => {
    return [
    `/.well-known/apple-app-site-association`
    ] as const;
    }


export const getGetWellKnownAppleAppSiteAssociationQueryOptions = <TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWellKnownAppleAppSiteAssociationQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>> = ({ signal }) => getWellKnownAppleAppSiteAssociation({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWellKnownAppleAppSiteAssociationQueryResult = NonNullable<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>>
export type GetWellKnownAppleAppSiteAssociationQueryError = InternalHandlerHttpErrorResponse


export function useGetWellKnownAppleAppSiteAssociation<TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWellKnownAppleAppSiteAssociation<TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWellKnownAppleAppSiteAssociation<TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Apple App Site Association
 */

export function useGetWellKnownAppleAppSiteAssociation<TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWellKnownAppleAppSiteAssociationQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getWellKnownAssetlinksJsonResponse200 = {
  data: GetWellKnownAssetlinksJson200Item[]
  status: 200
}

export type getWellKnownAssetlinksJsonResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getWellKnownAssetlinksJsonResponseSuccess = (getWellKnownAssetlinksJsonResponse200) & {
  headers: Headers;
};
export type getWellKnownAssetlinksJsonResponseError = (getWellKnownAssetlinksJsonResponse404) & {
  headers: Headers;
};

export type getWellKnownAssetlinksJsonResponse = (getWellKnownAssetlinksJsonResponseSuccess | getWellKnownAssetlinksJsonResponseError)

export const getGetWellKnownAssetlinksJsonUrl = () => {




  return `/.well-known/assetlinks.json`
}

/**
 * Static JSON consumed by Android to enable App Links to `app.wakeup.client`. Returns 404 when `ANDROID_PACKAGE` or `ANDROID_SHA256_FINGERPRINTS` aren't configured. The fingerprints array supports signing-key rotation.
 * @summary Android Asset Links
 */
export const getWellKnownAssetlinksJson = async ( options?: RequestInit): Promise<getWellKnownAssetlinksJsonResponse> => {

  return orvalMutator<getWellKnownAssetlinksJsonResponse>(getGetWellKnownAssetlinksJsonUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetWellKnownAssetlinksJsonQueryKey = () => {
    return [
    `/.well-known/assetlinks.json`
    ] as const;
    }


export const getGetWellKnownAssetlinksJsonQueryOptions = <TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWellKnownAssetlinksJsonQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>> = ({ signal }) => getWellKnownAssetlinksJson({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWellKnownAssetlinksJsonQueryResult = NonNullable<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>>
export type GetWellKnownAssetlinksJsonQueryError = InternalHandlerHttpErrorResponse


export function useGetWellKnownAssetlinksJson<TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWellKnownAssetlinksJson<TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWellKnownAssetlinksJson<TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Android Asset Links
 */

export function useGetWellKnownAssetlinksJson<TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWellKnownAssetlinksJsonQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getV1HealthzResponse200 = {
  data: GithubComCadenlundWakeupAppsBackendInternalHandlerHttpHealthzResponse
  status: 200
}

export type getV1HealthzResponseSuccess = (getV1HealthzResponse200) & {
  headers: Headers;
};
;

export type getV1HealthzResponse = (getV1HealthzResponseSuccess)

export const getGetV1HealthzUrl = () => {




  return `/v1/healthz`
}

/**
 * Returns 200 with the process status and the minimum mobile-app version the server accepts. The load balancer uses this to confirm the process is running; it does not check downstream dependencies (use readyz for that). Mobile clients also read `min_client_version` for force-upgrade gating.
 * @summary Liveness probe
 */
export const getV1Healthz = async ( options?: RequestInit): Promise<getV1HealthzResponse> => {

  return orvalMutator<getV1HealthzResponse>(getGetV1HealthzUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1HealthzQueryKey = () => {
    return [
    `/v1/healthz`
    ] as const;
    }


export const getGetV1HealthzQueryOptions = <TData = Awaited<ReturnType<typeof getV1Healthz>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Healthz>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1HealthzQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Healthz>>> = ({ signal }) => getV1Healthz({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Healthz>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1HealthzQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Healthz>>>
export type GetV1HealthzQueryError = unknown


export function useGetV1Healthz<TData = Awaited<ReturnType<typeof getV1Healthz>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Healthz>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Healthz>>,
          TError,
          Awaited<ReturnType<typeof getV1Healthz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Healthz<TData = Awaited<ReturnType<typeof getV1Healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Healthz>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Healthz>>,
          TError,
          Awaited<ReturnType<typeof getV1Healthz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Healthz<TData = Awaited<ReturnType<typeof getV1Healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Healthz>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Liveness probe
 */

export function useGetV1Healthz<TData = Awaited<ReturnType<typeof getV1Healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Healthz>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1HealthzQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getV1OpenapiJsonResponse200 = {
  data: GetV1OpenapiJson200
  status: 200
}

export type getV1OpenapiJsonResponseSuccess = (getV1OpenapiJsonResponse200) & {
  headers: Headers;
};
;

export type getV1OpenapiJsonResponse = (getV1OpenapiJsonResponseSuccess)

export const getGetV1OpenapiJsonUrl = () => {




  return `/v1/openapi.json`
}

/**
 * Serves the generated OpenAPI 2.0 spec for this API. /v1/docs (Swagger UI) loads it from this endpoint.
 * @summary OpenAPI spec
 */
export const getV1OpenapiJson = async ( options?: RequestInit): Promise<getV1OpenapiJsonResponse> => {

  return orvalMutator<getV1OpenapiJsonResponse>(getGetV1OpenapiJsonUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1OpenapiJsonQueryKey = () => {
    return [
    `/v1/openapi.json`
    ] as const;
    }


export const getGetV1OpenapiJsonQueryOptions = <TData = Awaited<ReturnType<typeof getV1OpenapiJson>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1OpenapiJson>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1OpenapiJsonQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1OpenapiJson>>> = ({ signal }) => getV1OpenapiJson({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1OpenapiJson>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1OpenapiJsonQueryResult = NonNullable<Awaited<ReturnType<typeof getV1OpenapiJson>>>
export type GetV1OpenapiJsonQueryError = unknown


export function useGetV1OpenapiJson<TData = Awaited<ReturnType<typeof getV1OpenapiJson>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1OpenapiJson>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1OpenapiJson>>,
          TError,
          Awaited<ReturnType<typeof getV1OpenapiJson>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1OpenapiJson<TData = Awaited<ReturnType<typeof getV1OpenapiJson>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1OpenapiJson>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1OpenapiJson>>,
          TError,
          Awaited<ReturnType<typeof getV1OpenapiJson>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1OpenapiJson<TData = Awaited<ReturnType<typeof getV1OpenapiJson>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1OpenapiJson>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary OpenAPI spec
 */

export function useGetV1OpenapiJson<TData = Awaited<ReturnType<typeof getV1OpenapiJson>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1OpenapiJson>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1OpenapiJsonQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getV1ReadyzResponse200 = {
  data: string
  status: 200
}

export type getV1ReadyzResponse500 = {
  data: GithubComCadenlundWakeupAppsBackendInternalHandlerHttpErrorResponse
  status: 500
}

export type getV1ReadyzResponseSuccess = (getV1ReadyzResponse200) & {
  headers: Headers;
};
export type getV1ReadyzResponseError = (getV1ReadyzResponse500) & {
  headers: Headers;
};

export type getV1ReadyzResponse = (getV1ReadyzResponseSuccess | getV1ReadyzResponseError)

export const getGetV1ReadyzUrl = () => {




  return `/v1/readyz`
}

/**
 * Pings Postgres and Redis with independent 1.5s timeouts. Returns 200 only when both respond; otherwise 500 with a §4.4 envelope listing failed dependencies.
 * @summary Readiness probe
 */
export const getV1Readyz = async ( options?: RequestInit): Promise<getV1ReadyzResponse> => {

  return orvalMutator<getV1ReadyzResponse>(getGetV1ReadyzUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1ReadyzQueryKey = () => {
    return [
    `/v1/readyz`
    ] as const;
    }


export const getGetV1ReadyzQueryOptions = <TData = Awaited<ReturnType<typeof getV1Readyz>>, TError = GithubComCadenlundWakeupAppsBackendInternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Readyz>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1ReadyzQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Readyz>>> = ({ signal }) => getV1Readyz({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1Readyz>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1ReadyzQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Readyz>>>
export type GetV1ReadyzQueryError = GithubComCadenlundWakeupAppsBackendInternalHandlerHttpErrorResponse


export function useGetV1Readyz<TData = Awaited<ReturnType<typeof getV1Readyz>>, TError = GithubComCadenlundWakeupAppsBackendInternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Readyz>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Readyz>>,
          TError,
          Awaited<ReturnType<typeof getV1Readyz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Readyz<TData = Awaited<ReturnType<typeof getV1Readyz>>, TError = GithubComCadenlundWakeupAppsBackendInternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Readyz>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1Readyz>>,
          TError,
          Awaited<ReturnType<typeof getV1Readyz>>
        > , 'initialData'
      >, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Readyz<TData = Awaited<ReturnType<typeof getV1Readyz>>, TError = GithubComCadenlundWakeupAppsBackendInternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Readyz>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Readiness probe
 */

export function useGetV1Readyz<TData = Awaited<ReturnType<typeof getV1Readyz>>, TError = GithubComCadenlundWakeupAppsBackendInternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Readyz>>, TError, TData>>, request?: SecondParameter<typeof orvalMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1ReadyzQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






