/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetV1ConversationsIdMessagesParams,
  InternalHandlerHttpEditMessageRequest,
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpMessageListResponse,
  InternalHandlerHttpMessageReadsResponse,
  InternalHandlerHttpMessageResponse,
  InternalHandlerHttpSendMessageRequest
} from '../../model';

import { orvalMutator } from '../../orval-mutator';




export type getV1ConversationsIdMessagesResponse200 = {
  data: InternalHandlerHttpMessageListResponse
  status: 200
}

export type getV1ConversationsIdMessagesResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1ConversationsIdMessagesResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1ConversationsIdMessagesResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getV1ConversationsIdMessagesResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1ConversationsIdMessagesResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1ConversationsIdMessagesResponseSuccess = (getV1ConversationsIdMessagesResponse200) & {
  headers: Headers;
};
export type getV1ConversationsIdMessagesResponseError = (getV1ConversationsIdMessagesResponse400 | getV1ConversationsIdMessagesResponse401 | getV1ConversationsIdMessagesResponse404 | getV1ConversationsIdMessagesResponse429 | getV1ConversationsIdMessagesResponse500) & {
  headers: Headers;
};

export type getV1ConversationsIdMessagesResponse = (getV1ConversationsIdMessagesResponseSuccess | getV1ConversationsIdMessagesResponseError)

export const getGetV1ConversationsIdMessagesUrl = (id: string,
    params?: GetV1ConversationsIdMessagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/conversations/${id}/messages?${stringifiedParams}` : `/v1/conversations/${id}/messages`
}

/**
 * Returns a page of messages in the conversation keyset-paginated by `created_at DESC, id DESC` per §6.4. Soft-deleted rows are included so the §4.6 placeholder can render — `body` is blanked and `is_deleted=true` so the client can render "this message was deleted" without leaking the original text.
 * @summary List messages in a conversation
 */
export const getV1ConversationsIdMessages = async (id: string,
    params?: GetV1ConversationsIdMessagesParams, options?: RequestInit): Promise<getV1ConversationsIdMessagesResponse> => {

  return orvalMutator<getV1ConversationsIdMessagesResponse>(getGetV1ConversationsIdMessagesUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1ConversationsIdMessagesQueryKey = (id: string,
    params?: GetV1ConversationsIdMessagesParams,) => {
    return [
    `/v1/conversations/${id}/messages`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetV1ConversationsIdMessagesQueryOptions = <TData = Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError = InternalHandlerHttpErrorResponse>(id: string,
    params?: GetV1ConversationsIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1ConversationsIdMessagesQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1ConversationsIdMessages>>> = ({ signal }) => getV1ConversationsIdMessages(id,params, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1ConversationsIdMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof getV1ConversationsIdMessages>>>
export type GetV1ConversationsIdMessagesQueryError = InternalHandlerHttpErrorResponse


export function useGetV1ConversationsIdMessages<TData = Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError = InternalHandlerHttpErrorResponse>(
 id: string,
    params: undefined |  GetV1ConversationsIdMessagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1ConversationsIdMessages>>,
          TError,
          Awaited<ReturnType<typeof getV1ConversationsIdMessages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1ConversationsIdMessages<TData = Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError = InternalHandlerHttpErrorResponse>(
 id: string,
    params?: GetV1ConversationsIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1ConversationsIdMessages>>,
          TError,
          Awaited<ReturnType<typeof getV1ConversationsIdMessages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1ConversationsIdMessages<TData = Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError = InternalHandlerHttpErrorResponse>(
 id: string,
    params?: GetV1ConversationsIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List messages in a conversation
 */

export function useGetV1ConversationsIdMessages<TData = Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError = InternalHandlerHttpErrorResponse>(
 id: string,
    params?: GetV1ConversationsIdMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1ConversationsIdMessages>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1ConversationsIdMessagesQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1ConversationsIdMessagesResponse201 = {
  data: InternalHandlerHttpMessageResponse
  status: 201
}

export type postV1ConversationsIdMessagesResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1ConversationsIdMessagesResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1ConversationsIdMessagesResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type postV1ConversationsIdMessagesResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1ConversationsIdMessagesResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1ConversationsIdMessagesResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1ConversationsIdMessagesResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1ConversationsIdMessagesResponseSuccess = (postV1ConversationsIdMessagesResponse201) & {
  headers: Headers;
};
export type postV1ConversationsIdMessagesResponseError = (postV1ConversationsIdMessagesResponse400 | postV1ConversationsIdMessagesResponse401 | postV1ConversationsIdMessagesResponse404 | postV1ConversationsIdMessagesResponse413 | postV1ConversationsIdMessagesResponse422 | postV1ConversationsIdMessagesResponse429 | postV1ConversationsIdMessagesResponse500) & {
  headers: Headers;
};

export type postV1ConversationsIdMessagesResponse = (postV1ConversationsIdMessagesResponseSuccess | postV1ConversationsIdMessagesResponseError)

export const getPostV1ConversationsIdMessagesUrl = (id: string,) => {




  return `/v1/conversations/${id}/messages`
}

/**
 * Creates a new message in the conversation. The caller must be a member. `attachment_ids` link previously-uploaded attachments; `reply_to_message_id` must live in the same conversation (cross-conversation replies are rejected at 422). On success, fans out a `message.new` event on `conv:<id>:messages` per §4.5 / §7.2.
 * @summary Send a message
 */
export const postV1ConversationsIdMessages = async (id: string,
    internalHandlerHttpSendMessageRequest: InternalHandlerHttpSendMessageRequest, options?: RequestInit): Promise<postV1ConversationsIdMessagesResponse> => {

  return orvalMutator<postV1ConversationsIdMessagesResponse>(getPostV1ConversationsIdMessagesUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpSendMessageRequest,)
  }
);}




export const getPostV1ConversationsIdMessagesMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdMessages>>, TError,{id: string;data: InternalHandlerHttpSendMessageRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdMessages>>, TError,{id: string;data: InternalHandlerHttpSendMessageRequest}, TContext> => {

const mutationKey = ['postV1ConversationsIdMessages'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1ConversationsIdMessages>>, {id: string;data: InternalHandlerHttpSendMessageRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postV1ConversationsIdMessages(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1ConversationsIdMessagesMutationResult = NonNullable<Awaited<ReturnType<typeof postV1ConversationsIdMessages>>>
    export type PostV1ConversationsIdMessagesMutationBody = InternalHandlerHttpSendMessageRequest
    export type PostV1ConversationsIdMessagesMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Send a message
 */
export const usePostV1ConversationsIdMessages = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1ConversationsIdMessages>>, TError,{id: string;data: InternalHandlerHttpSendMessageRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1ConversationsIdMessages>>,
        TError,
        {id: string;data: InternalHandlerHttpSendMessageRequest},
        TContext
      > => {
      return useMutation(getPostV1ConversationsIdMessagesMutationOptions(options), queryClient);
    }
    export type deleteV1MessagesIdResponse204 = {
  data: void
  status: 204
}

export type deleteV1MessagesIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type deleteV1MessagesIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type deleteV1MessagesIdResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type deleteV1MessagesIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type deleteV1MessagesIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type deleteV1MessagesIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type deleteV1MessagesIdResponseSuccess = (deleteV1MessagesIdResponse204) & {
  headers: Headers;
};
export type deleteV1MessagesIdResponseError = (deleteV1MessagesIdResponse400 | deleteV1MessagesIdResponse401 | deleteV1MessagesIdResponse403 | deleteV1MessagesIdResponse404 | deleteV1MessagesIdResponse429 | deleteV1MessagesIdResponse500) & {
  headers: Headers;
};

export type deleteV1MessagesIdResponse = (deleteV1MessagesIdResponseSuccess | deleteV1MessagesIdResponseError)

export const getDeleteV1MessagesIdUrl = (id: string,) => {




  return `/v1/messages/${id}`
}

/**
 * Soft-deletes a message. Allowed for the original sender or for an admin of the conversation. The row stays in history with `is_deleted=true` and `body` blanked at the wire (§4.6 placeholder rendering). Idempotent: re-deleting an already-deleted message returns 204.
 * @summary Delete a message
 */
export const deleteV1MessagesId = async (id: string, options?: RequestInit): Promise<deleteV1MessagesIdResponse> => {

  return orvalMutator<deleteV1MessagesIdResponse>(getDeleteV1MessagesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteV1MessagesIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1MessagesId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteV1MessagesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteV1MessagesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1MessagesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteV1MessagesId(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteV1MessagesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1MessagesId>>>

    export type DeleteV1MessagesIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Delete a message
 */
export const useDeleteV1MessagesId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteV1MessagesId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteV1MessagesId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteV1MessagesIdMutationOptions(options), queryClient);
    }
    export type patchV1MessagesIdResponse200 = {
  data: InternalHandlerHttpMessageResponse
  status: 200
}

export type patchV1MessagesIdResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type patchV1MessagesIdResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type patchV1MessagesIdResponse403 = {
  data: InternalHandlerHttpErrorResponse
  status: 403
}

export type patchV1MessagesIdResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type patchV1MessagesIdResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type patchV1MessagesIdResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type patchV1MessagesIdResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type patchV1MessagesIdResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type patchV1MessagesIdResponseSuccess = (patchV1MessagesIdResponse200) & {
  headers: Headers;
};
export type patchV1MessagesIdResponseError = (patchV1MessagesIdResponse400 | patchV1MessagesIdResponse401 | patchV1MessagesIdResponse403 | patchV1MessagesIdResponse404 | patchV1MessagesIdResponse413 | patchV1MessagesIdResponse422 | patchV1MessagesIdResponse429 | patchV1MessagesIdResponse500) & {
  headers: Headers;
};

export type patchV1MessagesIdResponse = (patchV1MessagesIdResponseSuccess | patchV1MessagesIdResponseError)

export const getPatchV1MessagesIdUrl = (id: string,) => {




  return `/v1/messages/${id}`
}

/**
 * Updates the body of an existing message. Caller must be the original sender; otherwise 403. Refuses on already-deleted rows (404). On success, stamps `edited_at` and fans out a `message.edited` event.
 * @summary Edit a message
 */
export const patchV1MessagesId = async (id: string,
    internalHandlerHttpEditMessageRequest: InternalHandlerHttpEditMessageRequest, options?: RequestInit): Promise<patchV1MessagesIdResponse> => {

  return orvalMutator<patchV1MessagesIdResponse>(getPatchV1MessagesIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpEditMessageRequest,)
  }
);}




export const getPatchV1MessagesIdMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1MessagesId>>, TError,{id: string;data: InternalHandlerHttpEditMessageRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchV1MessagesId>>, TError,{id: string;data: InternalHandlerHttpEditMessageRequest}, TContext> => {

const mutationKey = ['patchV1MessagesId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchV1MessagesId>>, {id: string;data: InternalHandlerHttpEditMessageRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchV1MessagesId(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchV1MessagesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchV1MessagesId>>>
    export type PatchV1MessagesIdMutationBody = InternalHandlerHttpEditMessageRequest
    export type PatchV1MessagesIdMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Edit a message
 */
export const usePatchV1MessagesId = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchV1MessagesId>>, TError,{id: string;data: InternalHandlerHttpEditMessageRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchV1MessagesId>>,
        TError,
        {id: string;data: InternalHandlerHttpEditMessageRequest},
        TContext
      > => {
      return useMutation(getPatchV1MessagesIdMutationOptions(options), queryClient);
    }
    export type getV1MessagesIdReadsResponse200 = {
  data: InternalHandlerHttpMessageReadsResponse
  status: 200
}

export type getV1MessagesIdReadsResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type getV1MessagesIdReadsResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1MessagesIdReadsResponse404 = {
  data: InternalHandlerHttpErrorResponse
  status: 404
}

export type getV1MessagesIdReadsResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1MessagesIdReadsResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1MessagesIdReadsResponseSuccess = (getV1MessagesIdReadsResponse200) & {
  headers: Headers;
};
export type getV1MessagesIdReadsResponseError = (getV1MessagesIdReadsResponse400 | getV1MessagesIdReadsResponse401 | getV1MessagesIdReadsResponse404 | getV1MessagesIdReadsResponse429 | getV1MessagesIdReadsResponse500) & {
  headers: Headers;
};

export type getV1MessagesIdReadsResponse = (getV1MessagesIdReadsResponseSuccess | getV1MessagesIdReadsResponseError)

export const getGetV1MessagesIdReadsUrl = (id: string,) => {




  return `/v1/messages/${id}/reads`
}

/**
 * Returns who has marked the message as read, newest read first. Caller must be a member of the message's conversation; otherwise 404.
 * @summary List read receipts for a message
 */
export const getV1MessagesIdReads = async (id: string, options?: RequestInit): Promise<getV1MessagesIdReadsResponse> => {

  return orvalMutator<getV1MessagesIdReadsResponse>(getGetV1MessagesIdReadsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1MessagesIdReadsQueryKey = (id: string,) => {
    return [
    `/v1/messages/${id}/reads`
    ] as const;
    }


export const getGetV1MessagesIdReadsQueryOptions = <TData = Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError = InternalHandlerHttpErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1MessagesIdReadsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1MessagesIdReads>>> = ({ signal }) => getV1MessagesIdReads(id, { signal });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1MessagesIdReadsQueryResult = NonNullable<Awaited<ReturnType<typeof getV1MessagesIdReads>>>
export type GetV1MessagesIdReadsQueryError = InternalHandlerHttpErrorResponse


export function useGetV1MessagesIdReads<TData = Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MessagesIdReads>>,
          TError,
          Awaited<ReturnType<typeof getV1MessagesIdReads>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1MessagesIdReads<TData = Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1MessagesIdReads>>,
          TError,
          Awaited<ReturnType<typeof getV1MessagesIdReads>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1MessagesIdReads<TData = Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List read receipts for a message
 */

export function useGetV1MessagesIdReads<TData = Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError = InternalHandlerHttpErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MessagesIdReads>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1MessagesIdReadsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






