/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Wakeup API
 * Friend-graph chat backend. See docs/WAKEUP.md for the full spec.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalHandlerHttpErrorResponse,
  InternalHandlerHttpLoginRequest,
  InternalHandlerHttpLoginResponse,
  InternalHandlerHttpMeResponse,
  InternalHandlerHttpPasswordResetConfirmRequest,
  InternalHandlerHttpPasswordResetRequestRequest,
  InternalHandlerHttpRegisterRequest,
  InternalHandlerHttpRegisterResponse
} from '../../model';

import { orvalMutator } from '../../orval-mutator';




export type postV1AuthLoginResponse200 = {
  data: InternalHandlerHttpLoginResponse
  status: 200
}

export type postV1AuthLoginResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1AuthLoginResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1AuthLoginResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1AuthLoginResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1AuthLoginResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AuthLoginResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AuthLoginResponseSuccess = (postV1AuthLoginResponse200) & {
  headers: Headers;
};
export type postV1AuthLoginResponseError = (postV1AuthLoginResponse400 | postV1AuthLoginResponse401 | postV1AuthLoginResponse413 | postV1AuthLoginResponse422 | postV1AuthLoginResponse429 | postV1AuthLoginResponse500) & {
  headers: Headers;
};

export type postV1AuthLoginResponse = (postV1AuthLoginResponseSuccess | postV1AuthLoginResponseError)

export const getPostV1AuthLoginUrl = () => {




  return `/v1/auth/login`
}

/**
 * Verifies credentials and binds a session cookie. Same generic 401 for any failure path (no enumeration).
 * @summary Log in
 */
export const postV1AuthLogin = async (internalHandlerHttpLoginRequest: InternalHandlerHttpLoginRequest, options?: RequestInit): Promise<postV1AuthLoginResponse> => {

  return orvalMutator<postV1AuthLoginResponse>(getPostV1AuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpLoginRequest,)
  }
);}




export const getPostV1AuthLoginMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: InternalHandlerHttpLoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: InternalHandlerHttpLoginRequest}, TContext> => {

const mutationKey = ['postV1AuthLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthLogin>>, {data: InternalHandlerHttpLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogin>>>
    export type PostV1AuthLoginMutationBody = InternalHandlerHttpLoginRequest
    export type PostV1AuthLoginMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Log in
 */
export const usePostV1AuthLogin = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogin>>, TError,{data: InternalHandlerHttpLoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthLogin>>,
        TError,
        {data: InternalHandlerHttpLoginRequest},
        TContext
      > => {
      return useMutation(getPostV1AuthLoginMutationOptions(options), queryClient);
    }
    export type postV1AuthLogoutResponse204 = {
  data: void
  status: 204
}

export type postV1AuthLogoutResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AuthLogoutResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AuthLogoutResponseSuccess = (postV1AuthLogoutResponse204) & {
  headers: Headers;
};
export type postV1AuthLogoutResponseError = (postV1AuthLogoutResponse429 | postV1AuthLogoutResponse500) & {
  headers: Headers;
};

export type postV1AuthLogoutResponse = (postV1AuthLogoutResponseSuccess | postV1AuthLogoutResponseError)

export const getPostV1AuthLogoutUrl = () => {




  return `/v1/auth/logout`
}

/**
 * Destroys the current session cookie. Idempotent — missing session returns 204.
 * @summary Log out current session
 */
export const postV1AuthLogout = async ( options?: RequestInit): Promise<postV1AuthLogoutResponse> => {

  return orvalMutator<postV1AuthLogoutResponse>(getPostV1AuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1AuthLogoutMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postV1AuthLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthLogout>>, void> = () => {


          return  postV1AuthLogout()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogout>>>

    export type PostV1AuthLogoutMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Log out current session
 */
export const usePostV1AuthLogout = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostV1AuthLogoutMutationOptions(options), queryClient);
    }
    export type postV1AuthLogoutAllResponse204 = {
  data: void
  status: 204
}

export type postV1AuthLogoutAllResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1AuthLogoutAllResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AuthLogoutAllResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AuthLogoutAllResponseSuccess = (postV1AuthLogoutAllResponse204) & {
  headers: Headers;
};
export type postV1AuthLogoutAllResponseError = (postV1AuthLogoutAllResponse401 | postV1AuthLogoutAllResponse429 | postV1AuthLogoutAllResponse500) & {
  headers: Headers;
};

export type postV1AuthLogoutAllResponse = (postV1AuthLogoutAllResponseSuccess | postV1AuthLogoutAllResponseError)

export const getPostV1AuthLogoutAllUrl = () => {




  return `/v1/auth/logout-all`
}

/**
 * Destroys every active session for the authenticated user. Used for "sign out everywhere" or post-password-reset cleanup.
 * @summary Log out every active session for this user
 */
export const postV1AuthLogoutAll = async ( options?: RequestInit): Promise<postV1AuthLogoutAllResponse> => {

  return orvalMutator<postV1AuthLogoutAllResponse>(getPostV1AuthLogoutAllUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostV1AuthLogoutAllMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogoutAll>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogoutAll>>, TError,void, TContext> => {

const mutationKey = ['postV1AuthLogoutAll'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthLogoutAll>>, void> = () => {


          return  postV1AuthLogoutAll()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthLogoutAllMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogoutAll>>>

    export type PostV1AuthLogoutAllMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Log out every active session for this user
 */
export const usePostV1AuthLogoutAll = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogoutAll>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthLogoutAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostV1AuthLogoutAllMutationOptions(options), queryClient);
    }
    export type getV1AuthMeResponse200 = {
  data: InternalHandlerHttpMeResponse
  status: 200
}

export type getV1AuthMeResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type getV1AuthMeResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type getV1AuthMeResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type getV1AuthMeResponseSuccess = (getV1AuthMeResponse200) & {
  headers: Headers;
};
export type getV1AuthMeResponseError = (getV1AuthMeResponse401 | getV1AuthMeResponse429 | getV1AuthMeResponse500) & {
  headers: Headers;
};

export type getV1AuthMeResponse = (getV1AuthMeResponseSuccess | getV1AuthMeResponseError)

export const getGetV1AuthMeUrl = () => {




  return `/v1/auth/me`
}

/**
 * Returns the user backing the active session. Use this on app launch to populate the local user store.
 * @summary Get authenticated user
 */
export const getV1AuthMe = async ( options?: RequestInit): Promise<getV1AuthMeResponse> => {

  return orvalMutator<getV1AuthMeResponse>(getGetV1AuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetV1AuthMeQueryKey = () => {
    return [
    `/v1/auth/me`
    ] as const;
    }


export const getGetV1AuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getV1AuthMe>>, TError = InternalHandlerHttpErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AuthMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1AuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1AuthMe>>> = ({ signal }) => getV1AuthMe({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1AuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1AuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getV1AuthMe>>>
export type GetV1AuthMeQueryError = InternalHandlerHttpErrorResponse


export function useGetV1AuthMe<TData = Awaited<ReturnType<typeof getV1AuthMe>>, TError = InternalHandlerHttpErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AuthMe>>,
          TError,
          Awaited<ReturnType<typeof getV1AuthMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AuthMe<TData = Awaited<ReturnType<typeof getV1AuthMe>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1AuthMe>>,
          TError,
          Awaited<ReturnType<typeof getV1AuthMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1AuthMe<TData = Awaited<ReturnType<typeof getV1AuthMe>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AuthMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get authenticated user
 */

export function useGetV1AuthMe<TData = Awaited<ReturnType<typeof getV1AuthMe>>, TError = InternalHandlerHttpErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1AuthMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1AuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type postV1AuthPasswordResetConfirmResponse204 = {
  data: void
  status: 204
}

export type postV1AuthPasswordResetConfirmResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1AuthPasswordResetConfirmResponse401 = {
  data: InternalHandlerHttpErrorResponse
  status: 401
}

export type postV1AuthPasswordResetConfirmResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1AuthPasswordResetConfirmResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1AuthPasswordResetConfirmResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AuthPasswordResetConfirmResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AuthPasswordResetConfirmResponseSuccess = (postV1AuthPasswordResetConfirmResponse204) & {
  headers: Headers;
};
export type postV1AuthPasswordResetConfirmResponseError = (postV1AuthPasswordResetConfirmResponse400 | postV1AuthPasswordResetConfirmResponse401 | postV1AuthPasswordResetConfirmResponse413 | postV1AuthPasswordResetConfirmResponse422 | postV1AuthPasswordResetConfirmResponse429 | postV1AuthPasswordResetConfirmResponse500) & {
  headers: Headers;
};

export type postV1AuthPasswordResetConfirmResponse = (postV1AuthPasswordResetConfirmResponseSuccess | postV1AuthPasswordResetConfirmResponseError)

export const getPostV1AuthPasswordResetConfirmUrl = () => {




  return `/v1/auth/password-reset/confirm`
}

/**
 * Sets the user's new password if the token is valid + unused. Returns generic 401 on any failure (no oracle).
 * @summary Confirm a password reset
 */
export const postV1AuthPasswordResetConfirm = async (internalHandlerHttpPasswordResetConfirmRequest: InternalHandlerHttpPasswordResetConfirmRequest, options?: RequestInit): Promise<postV1AuthPasswordResetConfirmResponse> => {

  return orvalMutator<postV1AuthPasswordResetConfirmResponse>(getPostV1AuthPasswordResetConfirmUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpPasswordResetConfirmRequest,)
  }
);}




export const getPostV1AuthPasswordResetConfirmMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPasswordResetConfirm>>, TError,{data: InternalHandlerHttpPasswordResetConfirmRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPasswordResetConfirm>>, TError,{data: InternalHandlerHttpPasswordResetConfirmRequest}, TContext> => {

const mutationKey = ['postV1AuthPasswordResetConfirm'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthPasswordResetConfirm>>, {data: InternalHandlerHttpPasswordResetConfirmRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthPasswordResetConfirm(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthPasswordResetConfirmMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthPasswordResetConfirm>>>
    export type PostV1AuthPasswordResetConfirmMutationBody = InternalHandlerHttpPasswordResetConfirmRequest
    export type PostV1AuthPasswordResetConfirmMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Confirm a password reset
 */
export const usePostV1AuthPasswordResetConfirm = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPasswordResetConfirm>>, TError,{data: InternalHandlerHttpPasswordResetConfirmRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthPasswordResetConfirm>>,
        TError,
        {data: InternalHandlerHttpPasswordResetConfirmRequest},
        TContext
      > => {
      return useMutation(getPostV1AuthPasswordResetConfirmMutationOptions(options), queryClient);
    }
    export type postV1AuthPasswordResetRequestResponse204 = {
  data: void
  status: 204
}

export type postV1AuthPasswordResetRequestResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1AuthPasswordResetRequestResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1AuthPasswordResetRequestResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1AuthPasswordResetRequestResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AuthPasswordResetRequestResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AuthPasswordResetRequestResponseSuccess = (postV1AuthPasswordResetRequestResponse204) & {
  headers: Headers;
};
export type postV1AuthPasswordResetRequestResponseError = (postV1AuthPasswordResetRequestResponse400 | postV1AuthPasswordResetRequestResponse413 | postV1AuthPasswordResetRequestResponse422 | postV1AuthPasswordResetRequestResponse429 | postV1AuthPasswordResetRequestResponse500) & {
  headers: Headers;
};

export type postV1AuthPasswordResetRequestResponse = (postV1AuthPasswordResetRequestResponseSuccess | postV1AuthPasswordResetRequestResponseError)

export const getPostV1AuthPasswordResetRequestUrl = () => {




  return `/v1/auth/password-reset/request`
}

/**
 * Generates a reset token and emails it. Always returns 204 even when the email is unknown — defeats account enumeration.
 * @summary Request a password reset
 */
export const postV1AuthPasswordResetRequest = async (internalHandlerHttpPasswordResetRequestRequest: InternalHandlerHttpPasswordResetRequestRequest, options?: RequestInit): Promise<postV1AuthPasswordResetRequestResponse> => {

  return orvalMutator<postV1AuthPasswordResetRequestResponse>(getPostV1AuthPasswordResetRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpPasswordResetRequestRequest,)
  }
);}




export const getPostV1AuthPasswordResetRequestMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPasswordResetRequest>>, TError,{data: InternalHandlerHttpPasswordResetRequestRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPasswordResetRequest>>, TError,{data: InternalHandlerHttpPasswordResetRequestRequest}, TContext> => {

const mutationKey = ['postV1AuthPasswordResetRequest'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthPasswordResetRequest>>, {data: InternalHandlerHttpPasswordResetRequestRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthPasswordResetRequest(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthPasswordResetRequestMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthPasswordResetRequest>>>
    export type PostV1AuthPasswordResetRequestMutationBody = InternalHandlerHttpPasswordResetRequestRequest
    export type PostV1AuthPasswordResetRequestMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Request a password reset
 */
export const usePostV1AuthPasswordResetRequest = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPasswordResetRequest>>, TError,{data: InternalHandlerHttpPasswordResetRequestRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthPasswordResetRequest>>,
        TError,
        {data: InternalHandlerHttpPasswordResetRequestRequest},
        TContext
      > => {
      return useMutation(getPostV1AuthPasswordResetRequestMutationOptions(options), queryClient);
    }
    export type postV1AuthRegisterResponse201 = {
  data: InternalHandlerHttpRegisterResponse
  status: 201
}

export type postV1AuthRegisterResponse400 = {
  data: InternalHandlerHttpErrorResponse
  status: 400
}

export type postV1AuthRegisterResponse409 = {
  data: InternalHandlerHttpErrorResponse
  status: 409
}

export type postV1AuthRegisterResponse413 = {
  data: InternalHandlerHttpErrorResponse
  status: 413
}

export type postV1AuthRegisterResponse422 = {
  data: InternalHandlerHttpErrorResponse
  status: 422
}

export type postV1AuthRegisterResponse429 = {
  data: InternalHandlerHttpErrorResponse
  status: 429
}

export type postV1AuthRegisterResponse500 = {
  data: InternalHandlerHttpErrorResponse
  status: 500
}

export type postV1AuthRegisterResponseSuccess = (postV1AuthRegisterResponse201) & {
  headers: Headers;
};
export type postV1AuthRegisterResponseError = (postV1AuthRegisterResponse400 | postV1AuthRegisterResponse409 | postV1AuthRegisterResponse413 | postV1AuthRegisterResponse422 | postV1AuthRegisterResponse429 | postV1AuthRegisterResponse500) & {
  headers: Headers;
};

export type postV1AuthRegisterResponse = (postV1AuthRegisterResponseSuccess | postV1AuthRegisterResponseError)

export const getPostV1AuthRegisterUrl = () => {




  return `/v1/auth/register`
}

/**
 * Creates a new user account, hashes the password with argon2id, and binds the new session cookie.
 * @summary Register a new user
 */
export const postV1AuthRegister = async (internalHandlerHttpRegisterRequest: InternalHandlerHttpRegisterRequest, options?: RequestInit): Promise<postV1AuthRegisterResponse> => {

  return orvalMutator<postV1AuthRegisterResponse>(getPostV1AuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalHandlerHttpRegisterRequest,)
  }
);}




export const getPostV1AuthRegisterMutationOptions = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthRegister>>, TError,{data: InternalHandlerHttpRegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthRegister>>, TError,{data: InternalHandlerHttpRegisterRequest}, TContext> => {

const mutationKey = ['postV1AuthRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthRegister>>, {data: InternalHandlerHttpRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthRegister(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthRegister>>>
    export type PostV1AuthRegisterMutationBody = InternalHandlerHttpRegisterRequest
    export type PostV1AuthRegisterMutationError = InternalHandlerHttpErrorResponse

    /**
 * @summary Register a new user
 */
export const usePostV1AuthRegister = <TError = InternalHandlerHttpErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthRegister>>, TError,{data: InternalHandlerHttpRegisterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthRegister>>,
        TError,
        {data: InternalHandlerHttpRegisterRequest},
        TContext
      > => {
      return useMutation(getPostV1AuthRegisterMutationOptions(options), queryClient);
    }
